# Import Event Log

In [1]:
import pandas as pd
import numpy as np
import pm4py
from pm4py.objects.conversion.log import converter as log_converter

if __name__ == "__main__":
    # Read the XES file
    dataframe_log = pm4py.read_xes('../../data/logs/InternationalDeclarations.xes')

    # If 'log' is already a DataFrame, add the @@case_index column directly
    case_indices = {case_id: idx for idx, case_id in enumerate(dataframe_log['case:concept:name'].unique())}
    dataframe_log['@@case_index'] = dataframe_log['case:concept:name'].map(case_indices)
    
     # Convert the dataframe to event log
    log = log_converter.apply(dataframe_log)
    
dataframe_log

/opt/anaconda3/lib/python3.9/site-packages/pm4py/util/dt_parsing/parser.py:76: UserWarning: ISO8601 strings are not fully supported with strpfromiso for Python versions below 3.11
  warnings.warn(

parsing log, completed traces ::   0%|          | 0/6449 [00:00<?, ?it/s]

,id,org:resource,concept:name,time:timestamp,org:role,case:Permit travel permit number,case:DeclarationNumber,case:Amount,case:RequestedAmount,case:Permit TaskNumber,...,case:Permit OrganizationalEntity,case:travel permit number,case:Permit RequestedBudget,case:id,case:Permit ID,case:Permit id,case:BudgetNumber,case:Permit ActivityNumber,case:AdjustedAmount,@@case_index
0,rv_travel permit 76455_6,STAFF MEMBER,Start trip,2016-10-04 22:00:00+00:00,EMPLOYEE,travel permit number 76456,declaration number 76458,39.664561,39.664561,UNKNOWN,...,organizational unit 65458,travel permit number 76456,41.613445,declaration 76457,travel permit 76455,travel permit 76455,budget 144133,activity 46005,39.664561,0
1,rv_travel permit 76455_7,STAFF MEMBER,End trip,2016-10-04 22:00:00+00:00,EMPLOYEE,travel permit number 76456,declaration number 76458,39.664561,39.664561,UNKNOWN,...,organizational unit 65458,travel permit number 76456,41.613445,declaration 76457,travel permit 76455,travel permit 76455,budget 144133,activity 46005,39.664561,0
2,st_step 76459_0,STAFF MEMBER,Permit SUBMITTED by EMPLOYEE,2017-04-06 11:32:10+00:00,EMPLOYEE,travel permit number 76456,declaration number 76458,39.664561,39.664561,UNKNOWN,...,organizational unit 65458,travel permit number 76456,41.613445,declaration 76457,travel permit 76455,travel permit 76455,budget 144133,activity 46005,39.664561,0
3,st_step 76460_0,STAFF MEMBER,Permit FINAL_APPROVED by SUPERVISOR,2017-04-06 11:32:28+00:00,SUPERVISOR,travel permit number 76456,declaration number 76458,39.664561,39.664561,UNKNOWN,...,organizational unit 65458,travel permit number 76456,41.613445,declaration 76457,travel permit 76455,travel permit 76455,budget 144133,activity 46005,39.664561,0
4,st_step 76461_0,STAFF MEMBER,Declaration SUBMITTED by EMPLOYEE,2017-04-07 11:38:14+00:00,EMPLOYEE,travel permit number 76456,declaration number 76458,39.664561,39.664561,UNKNOWN,...,organizational unit 65458,travel permit number 76456,41.613445,declaration 76457,travel permit 76455,travel permit 76455,budget 144133,activity 46005,39.664561,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72146,st_step 13239_0,STAFF MEMBER,Declaration SUBMITTED by EMPLOYEE,2018-12-18 14:06:50+00:00,EMPLOYEE,travel permit number 13227,UNKNOWN,0.000000,0.000000,task 427,...,organizational unit 65455,travel permit number 13227,1727.559756,declaration 13232,travel permit 13226,travel permit 13226,budget 147449,UNKNOWN,0.000000,6448
72147,st_step 13241_0,STAFF MEMBER,Declaration REJECTED by ADMINISTRATION,2018-12-18 14:06:57+00:00,ADMINISTRATION,travel permit number 13227,UNKNOWN,0.000000,0.000000,task 427,...,organizational unit 65455,travel permit number 13227,1727.559756,declaration 13232,travel permit 13226,travel permit 13226,budget 147449,UNKNOWN,0.000000,6448
72148,st_step 13240_0,STAFF MEMBER,Declaration REJECTED by EMPLOYEE,2018-12-19 13:05:36+00:00,EMPLOYEE,travel permit number 13227,UNKNOWN,0.000000,0.000000,task 427,...,organizational unit 65455,travel permit number 13227,1727.559756,declaration 13232,travel permit 13226,travel permit 13226,budget 147449,UNKNOWN,0.000000,6448
72149,rv_travel permit 13226_6,STAFF MEMBER,Start trip,2019-02-18 23:00:00+00:00,EMPLOYEE,travel permit number 13227,UNKNOWN,0.000000,0.000000,task 427,...,organizational unit 65455,travel permit number 13227,1727.559756,declaration 13232,travel permit 13226,travel permit 13226,budget 147449,UNKNOWN,0.000000,6448
72150,rv_travel permit 13226_7,STAFF MEMBER,End trip,2019-02-23 23:00:00+00:00,EMPLOYEE,travel permit number 13227,UNKNOWN,0.000000,0.000000,task 427,...,organizational unit 65455,travel permit number 13227,1727.559756,declaration 13232,travel permit 13226,travel permit 13226,budget 147449,UNKNOWN,0.000000,6448

In [2]:
# Function to check if an attribute has the same value across all different cases
def check_same_value_across_cases(dataframe_log, case_col, attr_col):
    # Group by case index and get unique values for the attribute in each case
    unique_values_per_case = dataframe_log.groupby(case_col)[attr_col].nunique()
    
    # Check if any case has more than one unique value for the attribute
    cases_with_multiple_values = unique_values_per_case[unique_values_per_case > 1]
    
    if cases_with_multiple_values.empty:
        print(f"The attribute '{attr_col}' has the same value across all cases.")
    else:
        print(f"The attribute '{attr_col}' does not have the same value across all cases.")
        print(f"Cases with multiple values for '{attr_col}':\n{cases_with_multiple_values}")

# Use the function with the example DataFrame
check_same_value_across_cases(dataframe_log, '@@case_index', 'id')

The attribute 'id' does not have the same value across all cases.
Cases with multiple values for 'id':
@@case_index
0        8
1        8
2        8
3       10
4       10
        ..
6444    12
6445    15
6446    12
6447     8
6448     8
Name: id, Length: 6449, dtype: int64

# Drop unnessary columns

In [3]:
dataframe_log = dataframe_log.drop(columns=['case:Permit ActivityNumber'])

In [4]:
dataframe_log = dataframe_log.drop(columns=['case:BudgetNumber'])

In [5]:
dataframe_log = dataframe_log.drop(columns=['case:Permit ID'])

In [6]:
dataframe_log = dataframe_log.drop(columns=['case:id'])

In [7]:
dataframe_log = dataframe_log.drop(columns=['case:travel permit number'])

In [8]:
dataframe_log = dataframe_log.drop(columns=['case:concept:name'])

In [9]:
dataframe_log = dataframe_log.drop(columns=['case:Permit ProjectNumber'])

In [10]:
dataframe_log = dataframe_log.drop(columns=['case:Permit TaskNumber'])

In [11]:
dataframe_log = dataframe_log.drop(columns=['case:DeclarationNumber'])

In [12]:
dataframe_log = dataframe_log.drop(columns=['case:Permit travel permit number'])

In [13]:
dataframe_log = dataframe_log.drop(columns=['case:Amount'])

In [14]:
dataframe_log = dataframe_log.drop(columns=['case:OriginalAmount'])

In [15]:
dataframe_log = dataframe_log.drop(columns=['case:AdjustedAmount'])

In [16]:
dataframe_log = dataframe_log.drop(columns=['case:Permit id'])

In [17]:
dataframe_log = dataframe_log.drop(columns=['case:Permit RequestedBudget'])

In [18]:
dataframe_log = dataframe_log.drop(columns=['case:Permit OrganizationalEntity'])

In [19]:
dataframe_log = dataframe_log.drop(columns=['case:Permit BudgetNumber'])

In [20]:
dataframe_log = dataframe_log.drop(columns=['case:RequestedAmount'])

In [21]:
from sklearn.preprocessing import StandardScaler

# Convert to datetime format
dataframe_log['time:timestamp'] = pd.to_datetime(dataframe_log['time:timestamp'])

# Calculate elapsed time since the start of each case
dataframe_log['start_time'] = dataframe_log.groupby('@@case_index')['time:timestamp'].transform('min')
dataframe_log['elapsed_time'] = (dataframe_log['time:timestamp'] - dataframe_log['start_time']).dt.total_seconds()

# Normalize the elapsed time in minutes
scaler = StandardScaler()
dataframe_log['standardized_elapsed_time'] = scaler.fit_transform(dataframe_log[['elapsed_time']])

dataframe_log = dataframe_log.drop(columns=['start_time'])
dataframe_log = dataframe_log.drop(columns=['elapsed_time'])
dataframe_log = dataframe_log.drop(columns=['time:timestamp'])

In [22]:
dataframe_log

,id,org:resource,concept:name,org:role,@@case_index,standardized_elapsed_time
0,rv_travel permit 76455_6,STAFF MEMBER,Start trip,EMPLOYEE,0,-0.800140
1,rv_travel permit 76455_7,STAFF MEMBER,End trip,EMPLOYEE,0,-0.800140
2,st_step 76459_0,STAFF MEMBER,Permit SUBMITTED by EMPLOYEE,EMPLOYEE,0,2.352533
3,st_step 76460_0,STAFF MEMBER,Permit FINAL_APPROVED by SUPERVISOR,SUPERVISOR,0,2.352537
4,st_step 76461_0,STAFF MEMBER,Declaration SUBMITTED by EMPLOYEE,EMPLOYEE,0,2.369780
...,...,...,...,...,...,...
72146,st_step 13239_0,STAFF MEMBER,Declaration SUBMITTED by EMPLOYEE,EMPLOYEE,6448,-0.730749
72147,st_step 13241_0,STAFF MEMBER,Declaration REJECTED by ADMINISTRATION,ADMINISTRATION,6448,-0.730748
72148,st_step 13240_0,STAFF MEMBER,Declaration REJECTED by EMPLOYEE,EMPLOYEE,6448,-0.714305
72149,rv_travel permit 13226_6,STAFF MEMBER,Start trip,EMPLOYEE,6448,0.340447
72150,rv_travel permit 13226_7,STAFF MEMBER,End trip,EMPLOYEE,6448,0.426321

# Insert Start & End markers

In [23]:
# Define a function to insert start and end markers
def add_markers(df):
    # Identify unique case indices
    case_indices = df['@@case_index'].unique()
    
    # Prepare a container for new DataFrame rows
    new_rows = []
    
    # Iterate over each case index to add start and end markers
    for case_index in case_indices:
        # Create a start marker row with all columns except @@case_index set to 'Start'
        start_row = {col: 'Start' if col != '@@case_index' else case_index for col in df.columns}
        
        # Create an end marker row with all columns except @@case_index set to 'End'
        end_row = {col: 'End' if col != '@@case_index' else case_index for col in df.columns}
        
        # Append start row, rows for the current case, and end row
        new_rows.append(start_row)
        new_rows.extend(df[df['@@case_index'] == case_index].to_dict('records'))
        new_rows.append(end_row)
    
    # Convert the list of rows into a DataFrame
    return pd.DataFrame(new_rows)

# Apply the function to add start and end markers to the dataframe
modified_dataframe = add_markers(dataframe_log)

In [24]:
modified_dataframe

,id,org:resource,concept:name,org:role,@@case_index,standardized_elapsed_time
0,Start,Start,Start,Start,0,Start
1,rv_travel permit 76455_6,STAFF MEMBER,Start trip,EMPLOYEE,0,-0.80014
2,rv_travel permit 76455_7,STAFF MEMBER,End trip,EMPLOYEE,0,-0.80014
3,st_step 76459_0,STAFF MEMBER,Permit SUBMITTED by EMPLOYEE,EMPLOYEE,0,2.352533
4,st_step 76460_0,STAFF MEMBER,Permit FINAL_APPROVED by SUPERVISOR,SUPERVISOR,0,2.352537
...,...,...,...,...,...,...
85044,st_step 13241_0,STAFF MEMBER,Declaration REJECTED by ADMINISTRATION,ADMINISTRATION,6448,-0.730748
85045,st_step 13240_0,STAFF MEMBER,Declaration REJECTED by EMPLOYEE,EMPLOYEE,6448,-0.714305
85046,rv_travel permit 13226_6,STAFF MEMBER,Start trip,EMPLOYEE,6448,0.340447
85047,rv_travel permit 13226_7,STAFF MEMBER,End trip,EMPLOYEE,6448,0.426321
85048,End,End,End,End,6448,End

# Preprocess

In [26]:
modified_dataframe['standardized_elapsed_time'] = modified_dataframe['standardized_elapsed_time'].replace({'Start': 0, 'End': 1})

In [25]:
modified_dataframe

,id,org:resource,concept:name,org:role,@@case_index,normalized_elapsed_time
0,Start,Start,Start,Start,0,0.000000
1,rv_travel permit 76455_6,STAFF MEMBER,Start trip,EMPLOYEE,0,0.000000
2,rv_travel permit 76455_7,STAFF MEMBER,End trip,EMPLOYEE,0,0.000000
3,st_step 76459_0,STAFF MEMBER,Permit SUBMITTED by EMPLOYEE,EMPLOYEE,0,0.247391
4,st_step 76460_0,STAFF MEMBER,Permit FINAL_APPROVED by SUPERVISOR,SUPERVISOR,0,0.247391
...,...,...,...,...,...,...
85044,st_step 13241_0,STAFF MEMBER,Declaration REJECTED by ADMINISTRATION,ADMINISTRATION,6448,0.005445
85045,st_step 13240_0,STAFF MEMBER,Declaration REJECTED by EMPLOYEE,EMPLOYEE,6448,0.006735
85046,rv_travel permit 13226_6,STAFF MEMBER,Start trip,EMPLOYEE,6448,0.089502
85047,rv_travel permit 13226_7,STAFF MEMBER,End trip,EMPLOYEE,6448,0.096241
85048,End,End,End,End,6448,1.000000

In [27]:
codes, uniques = pd.factorize(modified_dataframe['id'])
modified_dataframe['id'] = codes

In [28]:
codes, uniques = pd.factorize(modified_dataframe['org:resource'])
modified_dataframe['org:resource'] = codes

In [29]:
codes, uniques = pd.factorize(modified_dataframe['concept:name'])
modified_dataframe['concept:name'] = codes

In [30]:
codes, uniques = pd.factorize(modified_dataframe['org:role'])
modified_dataframe['org:role'] = codes

In [31]:
modified_dataframe

,id,org:resource,concept:name,org:role,@@case_index,standardized_elapsed_time
0,0,0,0,0,0,0.000000
1,1,1,1,1,0,-0.800140
2,2,1,2,1,0,-0.800140
3,3,1,3,1,0,2.352533
4,4,1,4,2,0,2.352537
...,...,...,...,...,...,...
85044,69071,1,30,7,6448,-0.730748
85045,69072,1,16,1,6448,-0.714305
85046,69073,1,1,1,6448,0.340447
85047,69074,1,2,1,6448,0.426321
85048,9,3,9,4,6448,1.000000

### Padding for Cases with less then 5 events

In [32]:
# Calculating the frequency of each unique value in '@@case_index'
frequency = modified_dataframe['@@case_index'].value_counts()

# Finding the minimum occurrence
min_occurrence = frequency.min()

min_occurrence

5

# Generate sliding windows

In [34]:
df_id = modified_dataframe[['id', '@@case_index']]
df_resource = modified_dataframe[['org:resource', '@@case_index']]
df_activity = modified_dataframe[['concept:name', '@@case_index']]
df_role = modified_dataframe[['org:role', '@@case_index']]
df_timestamp = modified_dataframe[['standardized_elapsed_time', '@@case_index']]

In [35]:
def generate_sliding_windows(df, case_id_column='@@case_index', window_size=5):
    windows = []
    targets = []
    case_indices = []

    # Iterate over each unique case
    for case_id in df[case_id_column].unique():
        # Extract the case
        case_data = df[df[case_id_column] == case_id]
        
        # Convert case_data to a NumPy array and drop the case_id_column
        case_data_array = case_data.drop(columns=[case_id_column]).to_numpy()

        # Adjusting the condition to correctly reflect window_size without needing an additional +1
        # Now it correctly considers window_size as including the target event
        if len(case_data_array) >= window_size:
            # Adjust the loop to generate sliding windows of size window_size - 1 for the inputs and use the next event as the target
            for i in range(len(case_data_array) - window_size + 1):
                # window now has window_size - 1 events
                window = case_data_array[i:i + window_size - 1]
                # The target is the event immediately following the window
                target = case_data_array[i + window_size - 1]
                windows.append(window)
                targets.append(target)
                case_indices.append(case_id)  # Store the case_id corresponding to the window

    # Convert lists to numpy arrays for easier handling and to ensure they are two-dimensional
    windows_array = np.array(windows)
    targets_array = np.array(targets)
    case_indices_array = np.array(case_indices)
    
    return windows_array, targets_array, case_indices_array

In [36]:
windows_id, targets_id, case_indices = generate_sliding_windows(df_id)
windows_resource, targets_resource, case_indices = generate_sliding_windows(df_resource)
windows_activity, targets_activity, case_indices = generate_sliding_windows(df_activity)
windows_role, targets_role, case_indices = generate_sliding_windows(df_role)
windows_timestamp, targets_timestamp, case_indices = generate_sliding_windows(df_timestamp)

# LSTM

### Architecture

- id not included because LSTm could not learn

In [37]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense, Concatenate, Embedding

# Assuming these values as placeholders, replace them with actual counts from your data
num_resources = modified_dataframe['org:resource'].nunique()
num_activities = modified_dataframe['concept:name'].nunique()
num_roles = modified_dataframe['org:role'].nunique()

embedding_dim_resource = 50
embedding_dim_activity = 50
embedding_dim_role = 50

time_steps = 4

# Input layers
input_resource = Input(shape=(time_steps,), name='input_resource')
input_activity = Input(shape=(time_steps,), name='input_activity')
input_role = Input(shape=(time_steps,), name='input_role')
input_timestamp = Input(shape=(time_steps, 1), name='input_timestamp')

# Embedding layers
embedding_resource = Embedding(input_dim=num_resources, output_dim=embedding_dim_resource, input_length=time_steps)(input_resource)
embedding_activity = Embedding(input_dim=num_activities, output_dim=embedding_dim_activity, input_length=time_steps)(input_activity)
embedding_role = Embedding(input_dim=num_roles, output_dim=embedding_dim_role, input_length=time_steps)(input_role)

# LSTM layers
lstm_resource = LSTM(25, return_sequences=False)(embedding_resource)
lstm_activity = LSTM(25, return_sequences=False)(embedding_activity)
lstm_role = LSTM(25, return_sequences=False)(embedding_role)
lstm_timestamp = LSTM(25, return_sequences=False)(input_timestamp)

# Concatenate outputs
concatenated = Concatenate(axis=-1)([lstm_resource, lstm_activity, lstm_role, lstm_timestamp])

# Output layers
output_resource = Dense(num_resources, activation='softmax', name='output_resource')(concatenated)
output_activity = Dense(num_activities, activation='softmax', name='output_activity')(concatenated)
output_role = Dense(num_roles, activation='softmax', name='output_role')(concatenated)
output_timestamp = Dense(1, activation='linear', name='output_timestamp')(concatenated)

# Create and compile the model
model = Model(inputs=[input_resource, input_activity, input_role, input_timestamp], 
              outputs=[output_resource, output_activity, output_role, output_timestamp])

model.compile(optimizer='adam', 
              loss={'output_resource': 'categorical_crossentropy', 
                    'output_activity': 'categorical_crossentropy',
                    'output_role': 'categorical_crossentropy', 
                    'output_timestamp': 'mean_squared_error'},
              metrics={'output_resource': 'accuracy', 
                       'output_activity': 'accuracy',
                       'output_role': 'accuracy', 
                       'output_timestamp': 'mean_absolute_error'})
model.summary()

2024-06-29 18:29:19.679394: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_resource (InputLayer  [(None, 4)]                  0         []
 )

 input_activity (InputLayer  [(None, 4)]                  0         []
 )

 input_role (InputLayer)     [(None, 4)]                  0         []

 embedding (Embedding)       (None, 4, 50)                200       ['input_resource[0][0]']

 embedding_1 (Embedding)     (None, 4, 50)                1800      ['input_activity[0][0]']

 embedding_2 (Embedding)     (None, 4, 50)                500       ['input_role[0][0]']

 input_timestamp (InputLaye  [(None, 4, 1)]               0         []
 r)

 lstm (LSTM)                 (None, 25)                   7600      ['embedding[0][0]']

 lstm_1 (LSTM)               (None, 25)                   7600      ['embedding_1[0][0]']

 lstm_2 (LSTM)               (None, 25)                   7600      ['embedding_2[0][0]']

 lstm_3 (LSTM)               (None, 25)                   2700      ['input_timestamp[0][0]']

 concatenate (Concatenate)   (None, 100)                  0         ['lstm[0][0]',
                                                                     'lstm_1[0][0]',
                                                                     'lstm_2[0][0]',
                                                                     'lstm_3[0][0]']

 output_resource (Dense)     (None, 4)                    404       ['concatenate[0][0]']

 output_activity (Dense)     (None, 36)                   3636      ['concatenate[0][0]']

 output_role (Dense)         (None, 10)                   1010      ['concatenate[0][0]']

 output_timestamp (Dense)    (None, 1)                    101       ['concatenate[0][0]']

==================================================================================================
Total params: 33151 (129.50 KB)
Trainable params: 33151 (129.50 KB)
Non-trainable params: 0 (0.00 Byte)
__________________________________________________________________________________________________

# Data Splitting

In [38]:
from sklearn.model_selection import train_test_split

# Split the resource data
train_resource, test_resource, train_targets_resource, test_targets_resource = train_test_split(
    windows_resource, targets_resource, test_size=0.2, random_state=42)

# Split the activity data
train_activity, test_activity, train_targets_activity, test_targets_activity = train_test_split(
    windows_activity, targets_activity, test_size=0.2, random_state=42)

# Split the role data
train_role, test_role, train_targets_role, test_targets_role = train_test_split(
    windows_role, targets_role, test_size=0.2, random_state=42)

# Split the timestamp data
train_timestamp, test_timestamp, train_targets_timestamp, test_targets_timestamp = train_test_split(
    windows_timestamp, targets_timestamp, test_size=0.2, random_state=42)

# Training

In [39]:
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import LearningRateScheduler

# EarlyStopping callback
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

def cyclic_lr(epoch, lr):
    # Example function that modulates LR within a range for each epoch
    # Customize this function based on your cyclic learning rate policy
    max_lr = 0.01  # Maximum LR
    base_lr = 0.001  # Base LR
    step_size = 10  # Number of epochs for half a cycle
    cycle = np.floor(1 + epoch / (2 * step_size))
    x = np.abs(epoch / step_size - 2 * cycle + 1)
    lr = base_lr + (max_lr - base_lr) * np.maximum(0, (1 - x))
    return lr

lr_scheduler = LearningRateScheduler(cyclic_lr)

In [40]:
import numpy as np
from tensorflow.keras.utils import to_categorical

train_targets_resource_cat = to_categorical(train_targets_resource, num_classes=num_resources)
test_targets_resource_cat = to_categorical(test_targets_resource, num_classes=num_resources)

train_targets_activity_cat = to_categorical(train_targets_activity, num_classes=num_activities)
test_targets_activity_cat = to_categorical(test_targets_activity, num_classes=num_activities)

train_targets_role_cat = to_categorical(train_targets_role, num_classes=num_roles)
test_targets_role_cat = to_categorical(test_targets_role, num_classes=num_roles)

# Note: Assuming timestamp targets are continuous and don't need to be converted to categorical

history = model.fit([train_resource, train_activity, train_role, train_timestamp], 
                    [train_targets_resource_cat, train_targets_activity_cat, train_targets_role_cat, train_targets_timestamp],
                    epochs=25,
                    batch_size=64,
                    validation_data=([test_resource, test_activity, test_role, test_timestamp], 
                                     [test_targets_resource_cat, test_targets_activity_cat, test_targets_role_cat, test_targets_timestamp]),
                    verbose=1,
                    callbacks=[lr_scheduler])  # Add other callbacks as needed

Epoch 1/25
741/741 [==============================] - 13s 8ms/step - loss: 2.5262 - output_resource_loss: 0.2459 - output_activity_loss: 1.1693 - output_role_loss: 0.6915 - output_timestamp_loss: 0.4195 - output_resource_accuracy: 0.9304 - output_activity_accuracy: 0.7085 - output_role_accuracy: 0.7931 - output_timestamp_mean_absolute_error: 0.3555 - val_loss: 1.2828 - val_output_resource_loss: 0.0953 - val_output_activity_loss: 0.5716 - val_output_role_loss: 0.3274 - val_output_timestamp_loss: 0.2885 - val_output_resource_accuracy: 0.9749 - val_output_activity_accuracy: 0.8366 - val_output_role_accuracy: 0.8944 - val_output_timestamp_mean_absolute_error: 0.2713 - lr: 0.0010
Epoch 2/25
741/741 [==============================] - 4s 5ms/step - loss: 1.1522 - output_resource_loss: 0.0861 - output_activity_loss: 0.5034 - output_role_loss: 0.2879 - output_timestamp_loss: 0.2747 - output_resource_accuracy: 0.9780 - output_activity_accuracy: 0.8495 - output_role_accuracy: 0.9040 - output_timestamp_mean_absolute_error: 0.2685 - val_loss: 1.0345 - val_output_resource_loss: 0.0682 - val_output_activity_loss: 0.4489 - val_output_role_loss: 0.2595 - val_output_timestamp_loss: 0.2579 - val_output_resource_accuracy: 0.9842 - val_output_activity_accuracy: 0.8609 - val_output_role_accuracy: 0.9104 - val_output_timestamp_mean_absolute_error: 0.2448 - lr: 0.0019
Epoch 3/25
741/741 [==============================] - 4s 6ms/step - loss: 1.0184 - output_resource_loss: 0.0745 - output_activity_loss: 0.4330 - output_role_loss: 0.2505 - output_timestamp_loss: 0.2604 - output_resource_accuracy: 0.9809 - output_activity_accuracy: 0.8623 - output_role_accuracy: 0.9104 - output_timestamp_mean_absolute_error: 0.2646 - val_loss: 0.9511 - val_output_resource_loss: 0.0614 - val_output_activity_loss: 0.4071 - val_output_role_loss: 0.2259 - val_output_timestamp_loss: 0.2566 - val_output_resource_accuracy: 0.9846 - val_output_activity_accuracy: 0.8679 - val_output_role_accuracy: 0.9167 - val_output_timestamp_mean_absolute_error: 0.2511 - lr: 0.0028
Epoch 4/25
741/741 [==============================] - 4s 6ms/step - loss: 0.9652 - output_resource_loss: 0.0724 - output_activity_loss: 0.4034 - output_role_loss: 0.2344 - output_timestamp_loss: 0.2550 - output_resource_accuracy: 0.9812 - output_activity_accuracy: 0.8687 - output_role_accuracy: 0.9154 - output_timestamp_mean_absolute_error: 0.2610 - val_loss: 0.9155 - val_output_resource_loss: 0.0582 - val_output_activity_loss: 0.3868 - val_output_role_loss: 0.2189 - val_output_timestamp_loss: 0.2516 - val_output_resource_accuracy: 0.9855 - val_output_activity_accuracy: 0.8712 - val_output_role_accuracy: 0.9187 - val_output_timestamp_mean_absolute_error: 0.2607 - lr: 0.0037
Epoch 5/25
741/741 [==============================] - 5s 7ms/step - loss: 0.9427 - output_resource_loss: 0.0700 - output_activity_loss: 0.3915 - output_role_loss: 0.2283 - output_timestamp_loss: 0.2529 - output_resource_accuracy: 0.9818 - output_activity_accuracy: 0.8691 - output_role_accuracy: 0.9159 - output_timestamp_mean_absolute_error: 0.2597 - val_loss: 0.9098 - val_output_resource_loss: 0.0570 - val_output_activity_loss: 0.3850 - val_output_role_loss: 0.2180 - val_output_timestamp_loss: 0.2497 - val_output_resource_accuracy: 0.9856 - val_output_activity_accuracy: 0.8712 - val_output_role_accuracy: 0.9175 - val_output_timestamp_mean_absolute_error: 0.2355 - lr: 0.0046
Epoch 6/25
741/741 [==============================] - 8s 10ms/step - loss: 0.9368 - output_resource_loss: 0.0701 - output_activity_loss: 0.3869 - output_role_loss: 0.2256 - output_timestamp_loss: 0.2543 - output_resource_accuracy: 0.9814 - output_activity_accuracy: 0.8695 - output_role_accuracy: 0.9166 - output_timestamp_mean_absolute_error: 0.2601 - val_loss: 0.9079 - val_output_resource_loss: 0.0600 - val_output_activity_loss: 0.3803 - val_output_role_loss: 0.2176 - val_output_timestamp_loss: 0.2500 - val_output_resource_accuracy: 0.9841 - val_output_activity_accuracy: 0.8685 - val_output_role_accuracy: 0.9086 - val_output_timestamp_mean_absolute_error: 0.2449 - lr: 0.0055
Epoch 7/25
741/741 [==============================] - 10s 13ms/step - loss: 0.9265 - output_resource_loss: 0.0690 - output_activity_loss: 0.3829 - output_role_loss: 0.2234 - output_timestamp_loss: 0.2512 - output_resource_accuracy: 0.9820 - output_activity_accuracy: 0.8722 - output_role_accuracy: 0.9177 - output_timestamp_mean_absolute_error: 0.2582 - val_loss: 0.9181 - val_output_resource_loss: 0.0581 - val_output_activity_loss: 0.3923 - val_output_role_loss: 0.2166 - val_output_timestamp_loss: 0.2511 - val_output_resource_accuracy: 0.9843 - val_output_activity_accuracy: 0.8706 - val_output_role_accuracy: 0.9182 - val_output_timestamp_mean_absolute_error: 0.2738 - lr: 0.0064
Epoch 8/25
741/741 [==============================] - 5s 7ms/step - loss: 0.9256 - output_resource_loss: 0.0695 - output_activity_loss: 0.3830 - output_role_loss: 0.2232 - output_timestamp_loss: 0.2499 - output_resource_accuracy: 0.9814 - output_activity_accuracy: 0.8697 - output_role_accuracy: 0.9165 - output_timestamp_mean_absolute_error: 0.2571 - val_loss: 0.9224 - val_output_resource_loss: 0.0586 - val_output_activity_loss: 0.3944 - val_output_role_loss: 0.2219 - val_output_timestamp_loss: 0.2475 - val_output_resource_accuracy: 0.9856 - val_output_activity_accuracy: 0.8674 - val_output_role_accuracy: 0.9131 - val_output_timestamp_mean_absolute_error: 0.2449 - lr: 0.0073
Epoch 9/25
741/741 [==============================] - 5s 6ms/step - loss: 0.9221 - output_resource_loss: 0.0681 - output_activity_loss: 0.3810 - output_role_loss: 0.2218 - output_timestamp_loss: 0.2512 - output_resource_accuracy: 0.9817 - output_activity_accuracy: 0.8709 - output_role_accuracy: 0.9174 - output_timestamp_mean_absolute_error: 0.2588 - val_loss: 0.8990 - val_output_resource_loss: 0.0556 - val_output_activity_loss: 0.3794 - val_output_role_loss: 0.2155 - val_output_timestamp_loss: 0.2484 - val_output_resource_accuracy: 0.9860 - val_output_activity_accuracy: 0.8729 - val_output_role_accuracy: 0.9175 - val_output_timestamp_mean_absolute_error: 0.2643 - lr: 0.0082
Epoch 10/25
741/741 [==============================] - 4s 6ms/step - loss: 0.9200 - output_resource_loss: 0.0686 - output_activity_loss: 0.3797 - output_role_loss: 0.2213 - output_timestamp_loss: 0.2504 - output_resource_accuracy: 0.9820 - output_activity_accuracy: 0.8717 - output_role_accuracy: 0.9175 - output_timestamp_mean_absolute_error: 0.2587 - val_loss: 0.9032 - val_output_resource_loss: 0.0609 - val_output_activity_loss: 0.3767 - val_output_role_loss: 0.2128 - val_output_timestamp_loss: 0.2528 - val_output_resource_accuracy: 0.9841 - val_output_activity_accuracy: 0.8721 - val_output_role_accuracy: 0.9202 - val_output_timestamp_mean_absolute_error: 0.2642 - lr: 0.0091
Epoch 11/25
741/741 [==============================] - 5s 7ms/step - loss: 0.9186 - output_resource_loss: 0.0693 - output_activity_loss: 0.3793 - output_role_loss: 0.2215 - output_timestamp_loss: 0.2485 - output_resource_accuracy: 0.9820 - output_activity_accuracy: 0.8713 - output_role_accuracy: 0.9175 - output_timestamp_mean_absolute_error: 0.2564 - val_loss: 0.9271 - val_output_resource_loss: 0.0599 - val_output_activity_loss: 0.3905 - val_output_role_loss: 0.2262 - val_output_timestamp_loss: 0.2504 - val_output_resource_accuracy: 0.9853 - val_output_activity_accuracy: 0.8693 - val_output_role_accuracy: 0.9171 - val_output_timestamp_mean_absolute_error: 0.2500 - lr: 0.0100
Epoch 12/25
741/741 [==============================] - 6s 8ms/step - loss: 0.9096 - output_resource_loss: 0.0675 - output_activity_loss: 0.3750 - output_role_loss: 0.2184 - output_timestamp_loss: 0.2487 - output_resource_accuracy: 0.9822 - output_activity_accuracy: 0.8728 - output_role_accuracy: 0.9193 - output_timestamp_mean_absolute_error: 0.2562 - val_loss: 0.9284 - val_output_resource_loss: 0.0653 - val_output_activity_loss: 0.3895 - val_output_role_loss: 0.2166 - val_output_timestamp_loss: 0.2570 - val_output_resource_accuracy: 0.9842 - val_output_activity_accuracy: 0.8681 - val_output_role_accuracy: 0.9172 - val_output_timestamp_mean_absolute_error: 0.2651 - lr: 0.0091
Epoch 13/25
741/741 [==============================] - 6s 8ms/step - loss: 0.8995 - output_resource_loss: 0.0667 - output_activity_loss: 0.3713 - output_role_loss: 0.2159 - output_timestamp_loss: 0.2456 - output_resource_accuracy: 0.9825 - output_activity_accuracy: 0.8728 - output_role_accuracy: 0.9184 - output_timestamp_mean_absolute_error: 0.2510 - val_loss: 0.8841 - val_output_resource_loss: 0.0555 - val_output_activity_loss: 0.3764 - val_output_role_loss: 0.2078 - val_output_timestamp_loss: 0.2444 - val_output_resource_accuracy: 0.9856 - val_output_activity_accuracy: 0.8726 - val_output_role_accuracy: 0.9209 - val_output_timestamp_mean_absolute_error: 0.2441 - lr: 0.0082
Epoch 14/25
741/741 [==============================] - 6s 8ms/step - loss: 0.8893 - output_resource_loss: 0.0658 - output_activity_loss: 0.3665 - output_role_loss: 0.2141 - output_timestamp_loss: 0.2428 - output_resource_accuracy: 0.9825 - output_activity_accuracy: 0.8744 - output_role_accuracy: 0.9192 - output_timestamp_mean_absolute_error: 0.2495 - val_loss: 0.8887 - val_output_resource_loss: 0.0587 - val_output_activity_loss: 0.3700 - val_output_role_loss: 0.2128 - val_output_timestamp_loss: 0.2472 - val_output_resource_accuracy: 0.9851 - val_output_activity_accuracy: 0.8743 - val_output_role_accuracy: 0.9201 - val_output_timestamp_mean_absolute_error: 0.2477 - lr: 0.0073
Epoch 15/25
741/741 [==============================] - 5s 7ms/step - loss: 0.8812 - output_resource_loss: 0.0650 - output_activity_loss: 0.3624 - output_role_loss: 0.2113 - output_timestamp_loss: 0.2425 - output_resource_accuracy: 0.9826 - output_activity_accuracy: 0.8751 - output_role_accuracy: 0.9200 - output_timestamp_mean_absolute_error: 0.2486 - val_loss: 0.8748 - val_output_resource_loss: 0.0563 - val_output_activity_loss: 0.3665 - val_output_role_loss: 0.2068 - val_output_timestamp_loss: 0.2453 - val_output_resource_accuracy: 0.9857 - val_output_activity_accuracy: 0.8723 - val_output_role_accuracy: 0.9179 - val_output_timestamp_mean_absolute_error: 0.2378 - lr: 0.0064
Epoch 16/25
741/741 [==============================] - 5s 7ms/step - loss: 0.8718 - output_resource_loss: 0.0645 - output_activity_loss: 0.3591 - output_role_loss: 0.2090 - output_timestamp_loss: 0.2392 - output_resource_accuracy: 0.9826 - output_activity_accuracy: 0.8761 - output_role_accuracy: 0.9202 - output_timestamp_mean_absolute_error: 0.2463 - val_loss: 0.8738 - val_output_resource_loss: 0.0552 - val_output_activity_loss: 0.3669 - val_output_role_loss: 0.2055 - val_output_timestamp_loss: 0.2462 - val_output_resource_accuracy: 0.9857 - val_output_activity_accuracy: 0.8746 - val_output_role_accuracy: 0.9216 - val_output_timestamp_mean_absolute_error: 0.2383 - lr: 0.0055
Epoch 17/25
741/741 [==============================] - 6s 8ms/step - loss: 0.8644 - output_resource_loss: 0.0637 - output_activity_loss: 0.3558 - output_role_loss: 0.2069 - output_timestamp_loss: 0.2380 - output_resource_accuracy: 0.9827 - output_activity_accuracy: 0.8765 - output_role_accuracy: 0.9206 - output_timestamp_mean_absolute_error: 0.2441 - val_loss: 0.8633 - val_output_resource_loss: 0.0555 - val_output_activity_loss: 0.3632 - val_output_role_loss: 0.2045 - val_output_timestamp_loss: 0.2401 - val_output_resource_accuracy: 0.9856 - val_output_activity_accuracy: 0.8729 - val_output_role_accuracy: 0.9205 - val_output_timestamp_mean_absolute_error: 0.2432 - lr: 0.0046
Epoch 18/25
741/741 [==============================] - 6s 8ms/step - loss: 0.8557 - output_resource_loss: 0.0632 - output_activity_loss: 0.3525 - output_role_loss: 0.2046 - output_timestamp_loss: 0.2355 - output_resource_accuracy: 0.9830 - output_activity_accuracy: 0.8775 - output_role_accuracy: 0.9217 - output_timestamp_mean_absolute_error: 0.2435 - val_loss: 0.8698 - val_output_resource_loss: 0.0546 - val_output_activity_loss: 0.3643 - val_output_role_loss: 0.2047 - val_output_timestamp_loss: 0.2462 - val_output_resource_accuracy: 0.9857 - val_output_activity_accuracy: 0.8745 - val_output_role_accuracy: 0.9210 - val_output_timestamp_mean_absolute_error: 0.2490 - lr: 0.0037
Epoch 19/25
741/741 [==============================] - 6s 8ms/step - loss: 0.8495 - output_resource_loss: 0.0627 - output_activity_loss: 0.3493 - output_role_loss: 0.2031 - output_timestamp_loss: 0.2344 - output_resource_accuracy: 0.9829 - output_activity_accuracy: 0.8775 - output_role_accuracy: 0.9214 - output_timestamp_mean_absolute_error: 0.2411 - val_loss: 0.8582 - val_output_resource_loss: 0.0551 - val_output_activity_loss: 0.3613 - val_output_role_loss: 0.2008 - val_output_timestamp_loss: 0.2411 - val_output_resource_accuracy: 0.9856 - val_output_activity_accuracy: 0.8727 - val_output_role_accuracy: 0.9218 - val_output_timestamp_mean_absolute_error: 0.2441 - lr: 0.0028
Epoch 20/25
741/741 [==============================] - 6s 8ms/step - loss: 0.8411 - output_resource_loss: 0.0620 - output_activity_loss: 0.3456 - output_role_loss: 0.2009 - output_timestamp_loss: 0.2326 - output_resource_accuracy: 0.9830 - output_activity_accuracy: 0.8786 - output_role_accuracy: 0.9219 - output_timestamp_mean_absolute_error: 0.2389 - val_loss: 0.8554 - val_output_resource_loss: 0.0548 - val_output_activity_loss: 0.3609 - val_output_role_loss: 0.2012 - val_output_timestamp_loss: 0.2385 - val_output_resource_accuracy: 0.9857 - val_output_activity_accuracy: 0.8749 - val_output_role_accuracy: 0.9210 - val_output_timestamp_mean_absolute_error: 0.2468 - lr: 0.0019
Epoch 21/25
741/741 [==============================] - 5s 7ms/step - loss: 0.8327 - output_resource_loss: 0.0613 - output_activity_loss: 0.3423 - output_role_loss: 0.1985 - output_timestamp_loss: 0.2306 - output_resource_accuracy: 0.9831 - output_activity_accuracy: 0.8797 - output_role_accuracy: 0.9226 - output_timestamp_mean_absolute_error: 0.2367 - val_loss: 0.8510 - val_output_resource_loss: 0.0547 - val_output_activity_loss: 0.3588 - val_output_role_loss: 0.2007 - val_output_timestamp_loss: 0.2368 - val_output_resource_accuracy: 0.9858 - val_output_activity_accuracy: 0.8743 - val_output_role_accuracy: 0.9214 - val_output_timestamp_mean_absolute_error: 0.2393 - lr: 0.0010
Epoch 22/25
741/741 [==============================] - 5s 7ms/step - loss: 0.8383 - output_resource_loss: 0.0618 - output_activity_loss: 0.3443 - output_role_loss: 0.1997 - output_timestamp_loss: 0.2325 - output_resource_accuracy: 0.9831 - output_activity_accuracy: 0.8790 - output_role_accuracy: 0.9227 - output_timestamp_mean_absolute_error: 0.2383 - val_loss: 0.8551 - val_output_resource_loss: 0.0551 - val_output_activity_loss: 0.3599 - val_output_role_loss: 0.2009 - val_output_timestamp_loss: 0.2392 - val_output_resource_accuracy: 0.9859 - val_output_activity_accuracy: 0.8744 - val_output_role_accuracy: 0.9211 - val_output_timestamp_mean_absolute_error: 0.2417 - lr: 0.0019
Epoch 23/25
741/741 [==============================] - 5s 7ms/step - loss: 0.8430 - output_resource_loss: 0.0620 - output_activity_loss: 0.3464 - output_role_loss: 0.2010 - output_timestamp_loss: 0.2337 - output_resource_accuracy: 0.9830 - output_activity_accuracy: 0.8777 - output_role_accuracy: 0.9222 - output_timestamp_mean_absolute_error: 0.2409 - val_loss: 0.8603 - val_output_resource_loss: 0.0554 - val_output_activity_loss: 0.3640 - val_output_role_loss: 0.2021 - val_output_timestamp_loss: 0.2388 - val_output_resource_accuracy: 0.9858 - val_output_activity_accuracy: 0.8739 - val_output_role_accuracy: 0.9219 - val_output_timestamp_mean_absolute_error: 0.2349 - lr: 0.0028
Epoch 24/25
741/741 [==============================] - 6s 8ms/step - loss: 0.8487 - output_resource_loss: 0.0626 - output_activity_loss: 0.3488 - output_role_loss: 0.2023 - output_timestamp_loss: 0.2349 - output_resource_accuracy: 0.9829 - output_activity_accuracy: 0.8777 - output_role_accuracy: 0.9211 - output_timestamp_mean_absolute_error: 0.2422 - val_loss: 0.8620 - val_output_resource_loss: 0.0546 - val_output_activity_loss: 0.3651 - val_output_role_loss: 0.2036 - val_output_timestamp_loss: 0.2388 - val_output_resource_accuracy: 0.9859 - val_output_activity_accuracy: 0.8749 - val_output_role_accuracy: 0.9214 - val_output_timestamp_mean_absolute_error: 0.2384 - lr: 0.0037
Epoch 25/25
741/741 [==============================] - 6s 8ms/step - loss: 0.8539 - output_resource_loss: 0.0629 - output_activity_loss: 0.3514 - output_role_loss: 0.2038 - output_timestamp_loss: 0.2358 - output_resource_accuracy: 0.9830 - output_activity_accuracy: 0.8764 - output_role_accuracy: 0.9207 - output_timestamp_mean_absolute_error: 0.2449 - val_loss: 0.8629 - val_output_resource_loss: 0.0549 - val_output_activity_loss: 0.3630 - val_output_role_loss: 0.2033 - val_output_timestamp_loss: 0.2418 - val_output_resource_accuracy: 0.9858 - val_output_activity_accuracy: 0.8743 - val_output_role_accuracy: 0.9198 - val_output_timestamp_mean_absolute_error: 0.2451 - lr: 0.0046

In [41]:
evaluation = model.evaluate(
    [test_resource, test_activity, test_role, test_timestamp],
    [test_targets_resource_cat, test_targets_activity_cat, test_targets_role_cat, test_targets_timestamp]
)

print(evaluation)

371/371 [==============================] - 1s 3ms/step - loss: 0.8629 - output_resource_loss: 0.0549 - output_activity_loss: 0.3630 - output_role_loss: 0.2033 - output_timestamp_loss: 0.2418 - output_resource_accuracy: 0.9858 - output_activity_accuracy: 0.8743 - output_role_accuracy: 0.9198 - output_timestamp_mean_absolute_error: 0.2451
[0.8629199862480164, 0.05487974360585213, 0.36298036575317383, 0.20325756072998047, 0.2418021261692047, 0.9858239889144897, 0.8742722272872925, 0.919838011264801, 0.2451121211051941]

In [42]:
# Save the model to an H5 file
model.save('dapnn_international.h5')

/opt/anaconda3/lib/python3.9/site-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [37]:
from tensorflow.keras.models import load_model

# Load the model from the H5 file
model = load_model('dapnn_international.h5')

# Optionally, you can print the model summary to verify it has loaded correctly
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_resource (InputLayer  [(None, 4)]                  0         []
 )

 input_activity (InputLayer  [(None, 4)]                  0         []
 )

 input_role (InputLayer)     [(None, 4)]                  0         []

 embedding (Embedding)       (None, 4, 50)                200       ['input_resource[0][0]']

 embedding_1 (Embedding)     (None, 4, 50)                1800      ['input_activity[0][0]']

 embedding_2 (Embedding)     (None, 4, 50)                500       ['input_role[0][0]']

 input_timestamp (InputLaye  [(None, 4, 1)]               0         []
 r)

 lstm (LSTM)                 (None, 25)                   7600      ['embedding[0][0]']

 lstm_1 (LSTM)               (None, 25)                   7600      ['embedding_1[0][0]']

 lstm_2 (LSTM)               (None, 25)                   7600      ['embedding_2[0][0]']

 lstm_3 (LSTM)               (None, 25)                   2700      ['input_timestamp[0][0]']

 concatenate (Concatenate)   (None, 100)                  0         ['lstm[0][0]',
                                                                     'lstm_1[0][0]',
                                                                     'lstm_2[0][0]',
                                                                     'lstm_3[0][0]']

 output_resource (Dense)     (None, 4)                    404       ['concatenate[0][0]']

 output_activity (Dense)     (None, 36)                   3636      ['concatenate[0][0]']

 output_role (Dense)         (None, 10)                   1010      ['concatenate[0][0]']

 output_timestamp (Dense)    (None, 1)                    101       ['concatenate[0][0]']

==================================================================================================
Total params: 33151 (129.50 KB)
Trainable params: 33151 (129.50 KB)
Non-trainable params: 0 (0.00 Byte)
__________________________________________________________________________________________________

# Anomaly Score Computation

In [43]:
# Generate predictions for all inputs
predictions = model.predict([windows_resource, windows_activity, windows_role, windows_timestamp])

# Extract predictions for categorical attributes (softmax probabilities)
predictions_resource = predictions[0]  # Resource predictions
predictions_activity = predictions[1]  # Activity predictions
predictions_role = predictions[2]      # Role predictions

# Extract predictions for numerical attribute (timestamp)
predictions_timestamp = predictions[3] # Timestamp predictions

1852/1852 [==============================] - 6s 2ms/step

In [44]:
import numpy as np
from tensorflow.keras.utils import to_categorical

def compute_anomaly_scores(predictions, actuals):
    # For categorical predictions, convert actuals to one-hot for comparison
    actuals_one_hot = to_categorical(actuals, num_classes=predictions.shape[-1])
    
    max_predictions = np.max(predictions, axis=-1)
    actual_predictions = np.sum(predictions * actuals_one_hot, axis=-1)  # Extract the probability of the actual class
    
    anomaly_scores = (max_predictions - actual_predictions) / max_predictions
    
    return anomaly_scores

# Assuming targets_id, targets_resource, targets_activity, targets_role are the true values for these attributes
anomaly_scores_resource = compute_anomaly_scores(predictions_resource, targets_resource)
anomaly_scores_activity = compute_anomaly_scores(predictions_activity, targets_activity)
anomaly_scores_role = compute_anomaly_scores(predictions_role, targets_role)

In [45]:
def compute_anomaly_scores_continuous(predictions, actuals, normalization_factor):
    """
    Compute anomaly scores for continuous attributes.
    
    Parameters:
    - predictions: numpy array of predicted values.
    - actuals: numpy array of actual values.
    - normalization_factor: normalization factor (e.g., standard deviation of the attribute).
    
    Returns:
    - numpy array of anomaly scores.
    """
    # Calculate absolute differences
    differences = np.abs(predictions - actuals)
    
    # Normalize the differences
    anomaly_scores = differences / normalization_factor
    
    return anomaly_scores

In [46]:
normalization_factor = np.std(targets_timestamp)       # Example normalization factor (standard deviation)
anomaly_scores_timestamp = compute_anomaly_scores_continuous(predictions_timestamp, targets_timestamp, normalization_factor)

In [49]:
def classify_cases(anomaly_scores_resource, anomaly_scores_activity, anomaly_scores_role, anomaly_scores_timestamp, threshold=0.98):
    # Ensure all inputs are numpy arrays of the same shape
    anomaly_scores_resource = np.array(anomaly_scores_resource).flatten()
    anomaly_scores_activity = np.array(anomaly_scores_activity).flatten()
    anomaly_scores_role = np.array(anomaly_scores_role).flatten()
    anomaly_scores_timestamp = np.array(anomaly_scores_timestamp).flatten()

    # Check if all arrays have the same length
    if not (len(anomaly_scores_resource) == len(anomaly_scores_activity) == len(anomaly_scores_role) == len(anomaly_scores_timestamp)):
        raise ValueError("All input anomaly scores must have the same length.")

    # Find the maximum anomaly score across all attributes for each case
    max_scores = np.maximum.reduce([anomaly_scores_resource, anomaly_scores_activity, anomaly_scores_role, anomaly_scores_timestamp])

    # Classify cases as anomalous if the maximum anomaly score exceeds the threshold
    anomalous_cases = max_scores > threshold
    
    return anomalous_cases

# Now use the anomaly scores for id, resource, activity, role, and timestamp in the classification
anomalous_cases = classify_cases(anomaly_scores_resource, anomaly_scores_activity, anomaly_scores_role, anomaly_scores_timestamp)

In [72]:
def classify_cases(anomaly_scores_activity, threshold=0.98):
    # Ensure all inputs are numpy arrays of the same shape
    anomaly_scores_activity = np.array(anomaly_scores_activity).flatten()

    # Find the maximum anomaly score across all attributes for each case
    max_scores = np.maximum.reduce([anomaly_scores_activity])

    # Classify cases as anomalous if the maximum anomaly score exceeds the threshold
    anomalous_cases = max_scores > threshold
    
    return anomalous_cases

# Now use the anomaly scores for id, resource, activity, role, and timestamp in the classification
anomalous_cases = classify_cases(anomaly_scores_activity)

In [73]:
anomalous_cases

array([False, False, False, ..., False, False, False])

# Mapping

### True: anomaly, False: no anomaly

In [74]:
import pandas as pd

# Create a DataFrame from the case_indices_array corresponding to case_resource
mapping = pd.DataFrame({'case': case_indices})
mapping['predicted'] = anomalous_cases
mapping

       case  predicted
0         0      False
1         0      False
2         0      False
3         0      False
4         0      False
...     ...        ...
59248  6448      False
59249  6448      False
59250  6448      False
59251  6448      False
59252  6448      False

[59253 rows x 2 columns]

In [75]:
case_prediction = mapping.groupby('case')['predicted'].any()
case_prediction

case
0       False
1       False
2       False
3        True
4        True
        ...
6444    False
6445    False
6446    False
6447    False
6448    False
Name: predicted, Length: 6449, dtype: bool

# Ground Truth

In [76]:
def generate_alignments_adjusted_tracecost_pkl(log, net, initial_marking, final_marking):
    from pm4py.algo.conformance.alignments.petri_net import algorithm as alignments
    from pm4py.algo.conformance.alignments.petri_net import variants
    from pm4py.objects.petri_net.utils import align_utils
    max_events=0
    for trace in log:
        counter=0
        for event in trace:
            counter+=1
        if counter > max_events:
            max_events=counter
    parameters={}
    parameters[alignments.Variants.VERSION_STATE_EQUATION_A_STAR.value.Parameters.PARAM_SYNC_COST_FUNCTION] = list(map(lambda i: .1*i, range(max_events*2)))
    parameters[alignments.Variants.VERSION_STATE_EQUATION_A_STAR.value.Parameters.PARAM_TRACE_COST_FUNCTION]=list(map(lambda i: align_utils.STD_MODEL_LOG_MOVE_COST-.1*i, range(max_events*2)))
    aligned_traces = alignments.apply_log(log, net, initial_marking, final_marking, variant=variants.state_equation_a_star, parameters=parameters)
    return aligned_traces

In [77]:
import pm4py
from pm4py.objects.log.importer.xes import importer as xes_importer
from pm4py.objects.bpmn.importer import importer as bpmn_importer
from pm4py.algo.conformance.alignments.petri_net import algorithm as alignments_petri

# 2. Import the given BPMN model
bpmn_graph = bpmn_importer.apply("../../data/model/Model_InternationalDeclarations.bpmn")

# 3. Convert the BPMN to a Petri net
net, initial_marking, final_marking = pm4py.convert_to_petri_net(bpmn_graph)

aligned_traces = generate_alignments_adjusted_tracecost_pkl(log, net, initial_marking, final_marking)

aligning log, completed variants ::   0%|          | 0/753 [00:00<?, ?it/s]

In [78]:
def extract_conformance_status_by_fitness(aligned_traces):
    conformance_status = []
    for alignment in aligned_traces:
        fitness = alignment['fitness']
        # If the fitness is 1.0, the trace is conforming
        if fitness == 1.0:
            conformance_status.append(1)
        else:
            conformance_status.append(0)
    return conformance_status

# Get the conformance status list from the aligned traces
conformance = extract_conformance_status_by_fitness(aligned_traces)

In [79]:
ground_truth = pd.DataFrame({'conformity': conformance})
ground_truth['predicted'] = case_prediction

# Convert False to 0 and True to 1
ground_truth['predicted'] = [int(value) for value in ground_truth['predicted']]
ground_truth['predicted'] = 1 - ground_truth['predicted']
ground_truth

      conformity  predicted
0              0          1
1              0          1
2              0          1
3              0          0
4              0          0
...          ...        ...
6444           1          1
6445           0          1
6446           1          1
6447           0          1
6448           0          1

[6449 rows x 2 columns]

# Evaluation

In [80]:
# Calculating TP, TN, FP, FN
TP = ((ground_truth['conformity'] == 1) & (ground_truth['predicted'] == 1)).sum()
TN = ((ground_truth['conformity'] == 0) & (ground_truth['predicted'] == 0)).sum()
FP = ((ground_truth['conformity'] == 0) & (ground_truth['predicted'] == 1)).sum()
FN = ((ground_truth['conformity'] == 1) & (ground_truth['predicted'] == 0)).sum()

In [81]:
# Calculate accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)
print(f"Accuracy: {accuracy:.3f}")

Accuracy: 0.452

In [82]:
# Calculate f1

precision = TP / (TP + FP)
recall = TP / (TP + FN)

f1 = 2 * ((precision * recall) / (precision + recall))
print(f"F1: {f1:.3f}")

F1: 0.584

### Dev (Non Conform Traces)

In [83]:
# Calculate precision for Dev
precision = TN / (TN + FN)
print(f"Precision: {precision:.3f}")

Precision: 0.925

In [84]:
# Calculate recall for Dev
recall = TN / (TN + FP)
print(f"Recall: {recall:.3f}")

Recall: 0.112

### No Dev (Conform Traces)

In [85]:
# Calculate precision for No Dev
precision = TP / (TP + FP)
print(f"Precision: {precision:.3f}")

Precision: 0.415

In [86]:
# Calculate recall for No Dev
recall = TP / (TP + FN)
print(f"Recall: {recall:.3f}")

Recall: 0.986

### AUC

In [87]:
import pandas as pd
from sklearn.metrics import roc_auc_score

# Assuming ground_truth is your DataFrame
# Make sure 'conformity' contains actual labels (0 or 1)
# and 'predicted' contains predicted probabilities or scores
auc_roc = roc_auc_score(ground_truth['conformity'], ground_truth['predicted'])
auc_roc

0.5488415069186826