# Import Event Log

In [1]:
import pandas as pd
import numpy as np
import pm4py
from pm4py.objects.conversion.log import converter as log_converter

if __name__ == "__main__":
    # Read the XES file
    dataframe_log = pm4py.read_xes('../../data/logs/PrepaidTravelCost.xes')

    # If 'log' is already a DataFrame, add the @@case_index column directly
    case_indices = {case_id: idx for idx, case_id in enumerate(dataframe_log['case:concept:name'].unique())}
    dataframe_log['@@case_index'] = dataframe_log['case:concept:name'].map(case_indices)
    
     # Convert the dataframe to event log
    log = log_converter.apply(dataframe_log)
    
dataframe_log

/opt/anaconda3/lib/python3.9/site-packages/pm4py/util/dt_parsing/parser.py:76: UserWarning: ISO8601 strings are not fully supported with strpfromiso for Python versions below 3.11
  warnings.warn(

parsing log, completed traces ::   0%|          | 0/2099 [00:00<?, ?it/s]

,id,org:resource,concept:name,time:timestamp,org:role,case:Rfp_id,case:Permit travel permit number,case:Task,case:OrganizationalEntity,case:RequestedAmount,...,case:Permit ProjectNumber,case:Project,case:concept:name,case:Permit OrganizationalEntity,case:Permit RequestedBudget,case:Cost Type,case:Permit id,case:Permit ActivityNumber,case:RfpNumber,@@case_index
0,st_step 73555_0,STAFF MEMBER,Permit SUBMITTED by EMPLOYEE,2017-01-09 13:48:43+00:00,EMPLOYEE,request for payment 73550,UNKNOWN,task 71977,organizational unit 65463,854.579838,...,UNKNOWN,project 503,request for payment 73550,organizational unit 65455,1979.272104,0,travel permit 73549,UNKNOWN,request for payment number 73551,0
1,st_step 73554_0,STAFF MEMBER,Permit FINAL_APPROVED by SUPERVISOR,2017-01-09 13:48:55+00:00,SUPERVISOR,request for payment 73550,UNKNOWN,task 71977,organizational unit 65463,854.579838,...,UNKNOWN,project 503,request for payment 73550,organizational unit 65455,1979.272104,0,travel permit 73549,UNKNOWN,request for payment number 73551,0
2,st_step 73558_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,2017-01-12 10:40:27+00:00,EMPLOYEE,request for payment 73550,UNKNOWN,task 71977,organizational unit 65463,854.579838,...,UNKNOWN,project 503,request for payment 73550,organizational unit 65455,1979.272104,0,travel permit 73549,UNKNOWN,request for payment number 73551,0
3,st_step 73559_0,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,2017-01-12 10:41:59+00:00,SUPERVISOR,request for payment 73550,UNKNOWN,task 71977,organizational unit 65463,854.579838,...,UNKNOWN,project 503,request for payment 73550,organizational unit 65455,1979.272104,0,travel permit 73549,UNKNOWN,request for payment number 73551,0
4,st_step 73557_0,STAFF MEMBER,Request For Payment REJECTED by MISSING,2017-01-12 10:53:07+00:00,MISSING,request for payment 73550,UNKNOWN,task 71977,organizational unit 65463,854.579838,...,UNKNOWN,project 503,request for payment 73550,organizational unit 65455,1979.272104,0,travel permit 73549,UNKNOWN,request for payment number 73551,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18241,st_step 186614_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,2018-12-30 19:16:15+00:00,EMPLOYEE,request for payment 186612,UNKNOWN,UNKNOWN,organizational unit 65462,96.739075,...,UNKNOWN,project 147531,request for payment 186612,UNKNOWN,0.000000,0,UNKNOWN,UNKNOWN,request for payment number 186613,2098
18242,st_step 186616_0,STAFF MEMBER,Request For Payment APPROVED by ADMINISTRATION,2018-12-30 19:16:25+00:00,ADMINISTRATION,request for payment 186612,UNKNOWN,UNKNOWN,organizational unit 65462,96.739075,...,UNKNOWN,project 147531,request for payment 186612,UNKNOWN,0.000000,0,UNKNOWN,UNKNOWN,request for payment number 186613,2098
18243,st_step 186615_0,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,2019-01-14 14:09:11+00:00,SUPERVISOR,request for payment 186612,UNKNOWN,UNKNOWN,organizational unit 65462,96.739075,...,UNKNOWN,project 147531,request for payment 186612,UNKNOWN,0.000000,0,UNKNOWN,UNKNOWN,request for payment number 186613,2098
18244,rp_request for payment 186612_15,SYSTEM,Request Payment,2019-01-15 06:02:45+00:00,UNDEFINED,request for payment 186612,UNKNOWN,UNKNOWN,organizational unit 65462,96.739075,...,UNKNOWN,project 147531,request for payment 186612,UNKNOWN,0.000000,0,UNKNOWN,UNKNOWN,request for payment number 186613,2098
18245,rp_request for payment 186612_16,SYSTEM,Payment Handled,2019-01-17 16:31:44+00:00,UNDEFINED,request for payment 186612,UNKNOWN,UNKNOWN,organizational unit 65462,96.739075,...,UNKNOWN,project 147531,request for payment 186612,UNKNOWN,0.000000,0,UNKNOWN,UNKNOWN,request for payment number 186613,2098

# Drop unnessary columns

In [2]:
dataframe_log = dataframe_log.drop(columns=['case:Rfp_id'])
dataframe_log = dataframe_log.drop(columns=['case:Permit travel permit number'])
dataframe_log = dataframe_log.drop(columns=['case:Task'])
dataframe_log = dataframe_log.drop(columns=['case:OrganizationalEntity'])
dataframe_log = dataframe_log.drop(columns=['case:RequestedAmount'])
dataframe_log = dataframe_log.drop(columns=['case:Permit TaskNumber'])
dataframe_log = dataframe_log.drop(columns=['case:Activity'])
dataframe_log = dataframe_log.drop(columns=['case:Permit BudgetNumber'])
dataframe_log = dataframe_log.drop(columns=['case:Permit ProjectNumber'])
dataframe_log = dataframe_log.drop(columns=['case:Project'])
dataframe_log = dataframe_log.drop(columns=['case:concept:name'])
dataframe_log = dataframe_log.drop(columns=['case:Permit OrganizationalEntity'])
dataframe_log = dataframe_log.drop(columns=['case:Permit RequestedBudget'])
dataframe_log = dataframe_log.drop(columns=['case:Cost Type'])
dataframe_log = dataframe_log.drop(columns=['case:Permit id'])
dataframe_log = dataframe_log.drop(columns=['case:Permit ActivityNumber'])
dataframe_log = dataframe_log.drop(columns=['case:RfpNumber'])

In [3]:
dataframe_log

,id,org:resource,concept:name,time:timestamp,org:role,@@case_index
0,st_step 73555_0,STAFF MEMBER,Permit SUBMITTED by EMPLOYEE,2017-01-09 13:48:43+00:00,EMPLOYEE,0
1,st_step 73554_0,STAFF MEMBER,Permit FINAL_APPROVED by SUPERVISOR,2017-01-09 13:48:55+00:00,SUPERVISOR,0
2,st_step 73558_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,2017-01-12 10:40:27+00:00,EMPLOYEE,0
3,st_step 73559_0,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,2017-01-12 10:41:59+00:00,SUPERVISOR,0
4,st_step 73557_0,STAFF MEMBER,Request For Payment REJECTED by MISSING,2017-01-12 10:53:07+00:00,MISSING,0
...,...,...,...,...,...,...
18241,st_step 186614_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,2018-12-30 19:16:15+00:00,EMPLOYEE,2098
18242,st_step 186616_0,STAFF MEMBER,Request For Payment APPROVED by ADMINISTRATION,2018-12-30 19:16:25+00:00,ADMINISTRATION,2098
18243,st_step 186615_0,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,2019-01-14 14:09:11+00:00,SUPERVISOR,2098
18244,rp_request for payment 186612_15,SYSTEM,Request Payment,2019-01-15 06:02:45+00:00,UNDEFINED,2098
18245,rp_request for payment 186612_16,SYSTEM,Payment Handled,2019-01-17 16:31:44+00:00,UNDEFINED,2098

# Preprocess

In [4]:
from sklearn.preprocessing import StandardScaler

# Convert to datetime format
dataframe_log['time:timestamp'] = pd.to_datetime(dataframe_log['time:timestamp'])

# Calculate elapsed time since the start of each case
dataframe_log['start_time'] = dataframe_log.groupby('@@case_index')['time:timestamp'].transform('min')
dataframe_log['elapsed_time'] = (dataframe_log['time:timestamp'] - dataframe_log['start_time']).dt.total_seconds()

# Normalize the elapsed time in minutes
scaler = StandardScaler()
dataframe_log['standardized_elapsed_time'] = scaler.fit_transform(dataframe_log[['elapsed_time']])

dataframe_log = dataframe_log.drop(columns=['start_time'])
dataframe_log = dataframe_log.drop(columns=['elapsed_time'])
dataframe_log = dataframe_log.drop(columns=['time:timestamp'])

In [5]:
codes, uniques = pd.factorize(dataframe_log['id'])
dataframe_log['id'] = codes + 1

In [6]:
codes, uniques = pd.factorize(dataframe_log['org:resource'])
dataframe_log['org:resource'] = codes + 1

In [7]:
codes, uniques = pd.factorize(dataframe_log['concept:name'])
dataframe_log['concept:name'] = codes + 1

In [8]:
codes, uniques = pd.factorize(dataframe_log['org:role'])
dataframe_log['org:role'] = codes + 1

In [9]:
dataframe_log

,id,org:resource,concept:name,org:role,@@case_index,standardized_elapsed_time
0,1,1,1,1,0,-0.601890
1,2,1,2,2,0,-0.601886
2,3,1,3,1,0,-0.514864
3,4,1,4,2,0,-0.514832
4,5,1,5,3,0,-0.514598
...,...,...,...,...,...,...
18241,16201,1,3,1,2098,-0.601890
18242,16202,1,22,7,2098,-0.601886
18243,16203,1,4,2,2098,-0.153403
18244,16204,2,7,4,2098,-0.133318
18245,16205,2,8,4,2098,-0.059410

# Generate Prefixes

In [10]:
df_id = dataframe_log[['id', '@@case_index']]
df_resource = dataframe_log[['org:resource', '@@case_index']]
df_activity = dataframe_log[['concept:name', '@@case_index']]
df_role = dataframe_log[['org:role', '@@case_index']]
df_timestamp = dataframe_log[['standardized_elapsed_time', '@@case_index']]

In [11]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

def generate_prefix_windows(df, case_id_column='@@case_index', max_len=None):
    windows = []
    targets = []
    case_indices = []
    
    for case_id in df[case_id_column].unique():
        case_data = df[df[case_id_column] == case_id].drop(columns=[case_id_column]).to_numpy()
        
        # Optional: Make sure to sort the case data if there's an implicit order (e.g., by timestamps)
        # case_data = case_data.sort_values(by='timestamp_column').to_numpy()  # Uncomment and adjust if needed
        
        for i in range(1, len(case_data)):
            window = case_data[:i]
            target = case_data[i]
            windows.append(window)
            targets.append(target)
            case_indices.append(case_id)
    
    if max_len is None:
        max_len = max(len(window) for window in windows)
    
    # Pad sequences
    windows_padded = pad_sequences(windows, maxlen=max_len, padding='post', dtype='float32')
    
    # Convert targets to numpy array
    targets_array = np.array(targets, dtype='float32')
    case_indices_array = np.array(case_indices)
    
    return windows_padded, targets_array, case_indices_array

2024-08-18 17:49:49.603558: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [12]:
windows_id, targets_id, case_indices = generate_prefix_windows(df_id)
windows_resource, targets_resource, case_indices = generate_prefix_windows(df_resource)
windows_activity, targets_activity, case_indices = generate_prefix_windows(df_activity)
windows_role, targets_role, case_indices = generate_prefix_windows(df_role)
windows_timestamp, targets_timestamp, case_indices = generate_prefix_windows(df_timestamp)

# GRU

### Architecture

In [13]:
# Group by the @@case_index column and count the rows in each group
case_lengths = dataframe_log.groupby('@@case_index').size()

# Find the maximum value among the case lengths
E = case_lengths.max()

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, GRU, Embedding, Dense, Dropout, Concatenate, BatchNormalization

def create_binetv3(num_ids, num_resources, num_activities, num_roles, embedding_dim, gru_units, dropout_rate):
    # Input layers for each attribute
    input_id = Input(shape=(None,), name='id_input')
    input_resource = Input(shape=(None,), name='resource_input')
    input_activity = Input(shape=(None,), name='activity_input')
    input_role = Input(shape=(None,), name='role_input')
    input_timestamp = Input(shape=(None, 1), name='timestamp_input')

    # Embedding layers for categorical attributes
    embedding_id = Embedding(input_dim=num_ids + 1, output_dim=embedding_dim, mask_zero=True, name='id_embedding')(input_id)
    embedding_resource = Embedding(input_dim=num_resources + 1, output_dim=embedding_dim, mask_zero=True, name='resource_embedding')(input_resource)
    embedding_activity = Embedding(input_dim=num_activities + 1, output_dim=embedding_dim, mask_zero=True, name='activity_embedding')(input_activity)
    embedding_role = Embedding(input_dim=num_roles + 1, output_dim=embedding_dim, mask_zero=True, name='role_embedding')(input_role)

    # Encoder GRUs with Batch Normalization for categorical attributes
    encoded_id = GRU(units=gru_units, return_sequences=True, name='id_encoder')(embedding_id)
    bn_id = BatchNormalization(name='bn_id')(encoded_id)
    encoded_resource = GRU(units=gru_units, return_sequences=True, name='resource_encoder')(embedding_resource)
    bn_resource = BatchNormalization(name='bn_resource')(encoded_resource)
    encoded_activity = GRU(units=gru_units, return_sequences=True, name='activity_encoder')(embedding_activity)
    bn_activity = BatchNormalization(name='bn_activity')(encoded_activity)
    encoded_role = GRU(units=gru_units, return_sequences=True, name='role_encoder')(embedding_role)
    bn_role = BatchNormalization(name='bn_role')(encoded_role)

    # Encoder GRU with Batch Normalization for continuous attribute
    encoded_timestamp = GRU(units=gru_units, return_sequences=True, name='timestamp_encoder')(input_timestamp)
    bn_timestamp = BatchNormalization(name='bn_timestamp')(encoded_timestamp)

    # Concatenation of encoded outputs
    concatenated = Concatenate(name='concatenate_encodings')([bn_id, bn_resource, bn_activity, bn_role, bn_timestamp])

    # Decoder GRU
    decoder_output = GRU(units=gru_units, return_sequences=False, name='decoder_gru')(concatenated)
    dropout_layer = Dropout(rate=dropout_rate, name='dropout')(decoder_output)

    # Output layers for predicting the next event's attributes
    output_id = Dense(num_ids + 1, activation='softmax', name='output_id')(dropout_layer)
    output_resource = Dense(num_resources + 1, activation='softmax', name='output_resource')(dropout_layer)
    output_activity = Dense(num_activities + 1, activation='softmax', name='output_activity')(dropout_layer)
    output_role = Dense(num_roles + 1, activation='softmax', name='output_role')(dropout_layer)
    output_timestamp = Dense(1, activation='linear', name='output_timestamp')(dropout_layer)

    # Building the model
    model = Model(inputs=[input_id, input_resource, input_activity, input_role, input_timestamp], outputs=[output_id, output_resource, output_activity, output_role, output_timestamp])
    model.compile(
        optimizer='adam', 
        loss={
            'output_id': 'categorical_crossentropy',
            'output_resource': 'categorical_crossentropy',
            'output_activity': 'categorical_crossentropy',
            'output_role': 'categorical_crossentropy',
            'output_timestamp': 'mse'
        },
        metrics={
            'output_id': ['accuracy'],
            'output_resource': ['accuracy'],
            'output_activity': ['accuracy'],
            'output_role': ['accuracy'],
            'output_timestamp': ['mse']
        }
    )

    return model

# Parameters
gru_units = int(2 * E) 
num_ids = dataframe_log['id'].max()
num_resources = dataframe_log['org:resource'].max()
num_activities = dataframe_log['concept:name'].max()
num_roles = dataframe_log['org:role'].max()
embedding_dim = 50
dropout_rate = 0.2
model = create_binetv3(num_ids, num_resources, num_activities, num_roles, embedding_dim, gru_units, dropout_rate)
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 id_input (InputLayer)       [(None, None)]               0         []

 resource_input (InputLayer  [(None, None)]               0         []
 )

 activity_input (InputLayer  [(None, None)]               0         []
 )

 role_input (InputLayer)     [(None, None)]               0         []

 id_embedding (Embedding)    (None, None, 50)             810300    ['id_input[0][0]']

 resource_embedding (Embedd  (None, None, 50)             150       ['resource_input[0][0]']
 ing)

 activity_embedding (Embedd  (None, None, 50)             1500      ['activity_input[0][0]']
 ing)

 role_embedding (Embedding)  (None, None, 50)             450       ['role_input[0][0]']

 timestamp_input (InputLaye  [(None, None, 1)]            0         []
 r)

 id_encoder (GRU)            (None, None, 42)             11844     ['id_embedding[0][0]']

 resource_encoder (GRU)      (None, None, 42)             11844     ['resource_embedding[0][0]']

 activity_encoder (GRU)      (None, None, 42)             11844     ['activity_embedding[0][0]']

 role_encoder (GRU)          (None, None, 42)             11844     ['role_embedding[0][0]']

 timestamp_encoder (GRU)     (None, None, 42)             5670      ['timestamp_input[0][0]']

 bn_id (BatchNormalization)  (None, None, 42)             168       ['id_encoder[0][0]']

 bn_resource (BatchNormaliz  (None, None, 42)             168       ['resource_encoder[0][0]']
 ation)

 bn_activity (BatchNormaliz  (None, None, 42)             168       ['activity_encoder[0][0]']
 ation)

 bn_role (BatchNormalizatio  (None, None, 42)             168       ['role_encoder[0][0]']
 n)

 bn_timestamp (BatchNormali  (None, None, 42)             168       ['timestamp_encoder[0][0]']
 zation)

 concatenate_encodings (Con  (None, None, 210)            0         ['bn_id[0][0]',
 catenate)                                                           'bn_resource[0][0]',
                                                                     'bn_activity[0][0]',
                                                                     'bn_role[0][0]',
                                                                     'bn_timestamp[0][0]']

 decoder_gru (GRU)           (None, 42)                   32004     ['concatenate_encodings[0][0]'
                                                                    ]

 dropout (Dropout)           (None, 42)                   0         ['decoder_gru[0][0]']

 output_id (Dense)           (None, 16206)                696858    ['dropout[0][0]']

 output_resource (Dense)     (None, 3)                    129       ['dropout[0][0]']

 output_activity (Dense)     (None, 30)                   1290      ['dropout[0][0]']

 output_role (Dense)         (None, 9)                    387       ['dropout[0][0]']

 output_timestamp (Dense)    (None, 1)                    43        ['dropout[0][0]']

==================================================================================================
Total params: 1596997 (6.09 MB)
Trainable params: 1596577 (6.09 MB)
Non-trainable params: 420 (1.64 KB)
__________________________________________________________________________________________________

### Data Splitting

In [15]:
from sklearn.model_selection import train_test_split

train_id, test_id, train_targets_id, test_targets_id = train_test_split(
    windows_id, targets_id, test_size=0.3, random_state=42)

train_resource, test_resource, train_targets_resource, test_targets_resource = train_test_split(
    windows_resource, targets_resource, test_size=0.3, random_state=42)

train_activity, test_activity, train_targets_activity, test_targets_activity = train_test_split(
    windows_activity, targets_activity, test_size=0.3, random_state=42)

train_role, test_role, train_targets_role, test_targets_role = train_test_split(
    windows_role, targets_role, test_size=0.3, random_state=42)

train_timestamp, test_timestamp, train_targets_timestamp, test_targets_timestamp = train_test_split(
    windows_timestamp, targets_timestamp, test_size=0.3, random_state=42)

### Training

In [16]:
from tensorflow.keras.utils import to_categorical

# One-hot encode the training and testing targets for each categorical attribute
train_targets_id_cat = to_categorical(train_targets_id, num_classes=num_ids + 1)
test_targets_id_cat = to_categorical(test_targets_id, num_classes=num_ids + 1)

train_targets_resource_cat = to_categorical(train_targets_resource, num_classes=num_resources + 1)
test_targets_resource_cat = to_categorical(test_targets_resource, num_classes=num_resources + 1)

train_targets_activity_cat = to_categorical(train_targets_activity, num_classes=num_activities + 1)
test_targets_activity_cat = to_categorical(test_targets_activity, num_classes=num_activities + 1)

train_targets_role_cat = to_categorical(train_targets_role, num_classes=num_roles + 1)
test_targets_role_cat = to_categorical(test_targets_role, num_classes=num_roles + 1)

In [17]:
# Fit the model with the properly shaped inputs and targets
history = model.fit(
    [train_id, train_resource, train_activity, train_role, train_timestamp],
    [train_targets_id_cat, train_targets_resource_cat, train_targets_activity_cat, train_targets_role_cat, train_targets_timestamp],
    validation_data=(
        [test_id, test_resource, test_activity, test_role, test_timestamp], 
        [test_targets_id_cat, test_targets_resource_cat, test_targets_activity_cat, test_targets_role_cat, test_targets_timestamp]
    ),
    epochs=20,
    batch_size=500
)

Epoch 1/20
23/23 [==============================] - 40s 759ms/step - loss: 15.5560 - output_id_loss: 9.7045 - output_resource_loss: 0.6332 - output_activity_loss: 2.9341 - output_role_loss: 1.8217 - output_timestamp_loss: 0.4625 - output_id_accuracy: 1.7696e-04 - output_resource_accuracy: 0.7733 - output_activity_accuracy: 0.2653 - output_role_accuracy: 0.3990 - output_timestamp_mse: 0.4625 - val_loss: 16.9134 - val_output_id_loss: 9.7080 - val_output_resource_loss: 0.8939 - val_output_activity_loss: 3.2251 - val_output_role_loss: 2.0480 - val_output_timestamp_loss: 1.0385 - val_output_id_accuracy: 0.0000e+00 - val_output_resource_accuracy: 0.8384 - val_output_activity_accuracy: 0.1880 - val_output_role_accuracy: 0.5090 - val_output_timestamp_mse: 1.0385
Epoch 2/20
23/23 [==============================] - 14s 611ms/step - loss: 13.1309 - output_id_loss: 9.5843 - output_resource_loss: 0.1685 - output_activity_loss: 1.9531 - output_role_loss: 1.0986 - output_timestamp_loss: 0.3265 - output_id_accuracy: 0.0023 - output_resource_accuracy: 0.9842 - output_activity_accuracy: 0.6043 - output_role_accuracy: 0.7302 - output_timestamp_mse: 0.3265 - val_loss: 16.4049 - val_output_id_loss: 9.7651 - val_output_resource_loss: 0.7229 - val_output_activity_loss: 3.0304 - val_output_role_loss: 1.8921 - val_output_timestamp_loss: 0.9944 - val_output_id_accuracy: 0.0019 - val_output_resource_accuracy: 0.8213 - val_output_activity_accuracy: 0.2279 - val_output_role_accuracy: 0.5886 - val_output_timestamp_mse: 0.9944
Epoch 3/20
23/23 [==============================] - 14s 592ms/step - loss: 11.8399 - output_id_loss: 9.3963 - output_resource_loss: 0.0792 - output_activity_loss: 1.3425 - output_role_loss: 0.7098 - output_timestamp_loss: 0.3122 - output_id_accuracy: 0.0034 - output_resource_accuracy: 0.9912 - output_activity_accuracy: 0.7020 - output_role_accuracy: 0.8164 - output_timestamp_mse: 0.3122 - val_loss: 16.0149 - val_output_id_loss: 9.8463 - val_output_resource_loss: 0.6054 - val_output_activity_loss: 2.8505 - val_output_role_loss: 1.7487 - val_output_timestamp_loss: 0.9641 - val_output_id_accuracy: 0.0029 - val_output_resource_accuracy: 0.8493 - val_output_activity_accuracy: 0.4190 - val_output_role_accuracy: 0.7191 - val_output_timestamp_mse: 0.9641
Epoch 4/20
23/23 [==============================] - 8s 357ms/step - loss: 11.0660 - output_id_loss: 9.2131 - output_resource_loss: 0.0579 - output_activity_loss: 1.0006 - output_role_loss: 0.5048 - output_timestamp_loss: 0.2897 - output_id_accuracy: 0.0034 - output_resource_accuracy: 0.9931 - output_activity_accuracy: 0.7769 - output_role_accuracy: 0.8611 - output_timestamp_mse: 0.2897 - val_loss: 15.6756 - val_output_id_loss: 9.9202 - val_output_resource_loss: 0.5399 - val_output_activity_loss: 2.6832 - val_output_role_loss: 1.6345 - val_output_timestamp_loss: 0.8977 - val_output_id_accuracy: 0.0031 - val_output_resource_accuracy: 0.8770 - val_output_activity_accuracy: 0.5996 - val_output_role_accuracy: 0.6729 - val_output_timestamp_mse: 0.8977
Epoch 5/20
23/23 [==============================] - 9s 391ms/step - loss: 10.5067 - output_id_loss: 9.0484 - output_resource_loss: 0.0490 - output_activity_loss: 0.7748 - output_role_loss: 0.3652 - output_timestamp_loss: 0.2693 - output_id_accuracy: 0.0031 - output_resource_accuracy: 0.9935 - output_activity_accuracy: 0.8314 - output_role_accuracy: 0.9113 - output_timestamp_mse: 0.2693 - val_loss: 15.3130 - val_output_id_loss: 10.0118 - val_output_resource_loss: 0.4543 - val_output_activity_loss: 2.5055 - val_output_role_loss: 1.4986 - val_output_timestamp_loss: 0.8428 - val_output_id_accuracy: 0.0033 - val_output_resource_accuracy: 0.8931 - val_output_activity_accuracy: 0.6832 - val_output_role_accuracy: 0.7071 - val_output_timestamp_mse: 0.8428
Epoch 6/20
23/23 [==============================] - 10s 450ms/step - loss: 10.0527 - output_id_loss: 8.8924 - output_resource_loss: 0.0416 - output_activity_loss: 0.6024 - output_role_loss: 0.2480 - output_timestamp_loss: 0.2683 - output_id_accuracy: 0.0037 - output_resource_accuracy: 0.9947 - output_activity_accuracy: 0.8748 - output_role_accuracy: 0.9492 - output_timestamp_mse: 0.2683 - val_loss: 14.9198 - val_output_id_loss: 10.1116 - val_output_resource_loss: 0.3781 - val_output_activity_loss: 2.3076 - val_output_role_loss: 1.3546 - val_output_timestamp_loss: 0.7680 - val_output_id_accuracy: 0.0035 - val_output_resource_accuracy: 0.8970 - val_output_activity_accuracy: 0.7331 - val_output_role_accuracy: 0.7408 - val_output_timestamp_mse: 0.7680
Epoch 7/20
23/23 [==============================] - 10s 439ms/step - loss: 9.6731 - output_id_loss: 8.7424 - output_resource_loss: 0.0358 - output_activity_loss: 0.4667 - output_role_loss: 0.1692 - output_timestamp_loss: 0.2589 - output_id_accuracy: 0.0046 - output_resource_accuracy: 0.9951 - output_activity_accuracy: 0.9030 - output_role_accuracy: 0.9728 - output_timestamp_mse: 0.2589 - val_loss: 14.5179 - val_output_id_loss: 10.2364 - val_output_resource_loss: 0.3085 - val_output_activity_loss: 2.0789 - val_output_role_loss: 1.1912 - val_output_timestamp_loss: 0.7029 - val_output_id_accuracy: 0.0035 - val_output_resource_accuracy: 0.9051 - val_output_activity_accuracy: 0.7447 - val_output_role_accuracy: 0.7738 - val_output_timestamp_mse: 0.7029
Epoch 8/20
23/23 [==============================] - 10s 445ms/step - loss: 9.3764 - output_id_loss: 8.5925 - output_resource_loss: 0.0305 - output_activity_loss: 0.3792 - output_role_loss: 0.1217 - output_timestamp_loss: 0.2525 - output_id_accuracy: 0.0055 - output_resource_accuracy: 0.9971 - output_activity_accuracy: 0.9225 - output_role_accuracy: 0.9843 - output_timestamp_mse: 0.2525 - val_loss: 14.1181 - val_output_id_loss: 10.4031 - val_output_resource_loss: 0.2439 - val_output_activity_loss: 1.8123 - val_output_role_loss: 1.0203 - val_output_timestamp_loss: 0.6386 - val_output_id_accuracy: 0.0033 - val_output_resource_accuracy: 0.9170 - val_output_activity_accuracy: 0.7463 - val_output_role_accuracy: 0.7905 - val_output_timestamp_mse: 0.6386
Epoch 9/20
23/23 [==============================] - 9s 408ms/step - loss: 9.1318 - output_id_loss: 8.4439 - output_resource_loss: 0.0262 - output_activity_loss: 0.3144 - output_role_loss: 0.0975 - output_timestamp_loss: 0.2498 - output_id_accuracy: 0.0058 - output_resource_accuracy: 0.9973 - output_activity_accuracy: 0.9362 - output_role_accuracy: 0.9877 - output_timestamp_mse: 0.2498 - val_loss: 13.8207 - val_output_id_loss: 10.6029 - val_output_resource_loss: 0.2085 - val_output_activity_loss: 1.5717 - val_output_role_loss: 0.8747 - val_output_timestamp_loss: 0.5630 - val_output_id_accuracy: 0.0033 - val_output_resource_accuracy: 0.9164 - val_output_activity_accuracy: 0.7465 - val_output_role_accuracy: 0.8093 - val_output_timestamp_mse: 0.5630
Epoch 10/20
23/23 [==============================] - 13s 587ms/step - loss: 8.9201 - output_id_loss: 8.3032 - output_resource_loss: 0.0241 - output_activity_loss: 0.2705 - output_role_loss: 0.0825 - output_timestamp_loss: 0.2398 - output_id_accuracy: 0.0074 - output_resource_accuracy: 0.9979 - output_activity_accuracy: 0.9474 - output_role_accuracy: 0.9895 - output_timestamp_mse: 0.2398 - val_loss: 13.5667 - val_output_id_loss: 10.7989 - val_output_resource_loss: 0.1727 - val_output_activity_loss: 1.3410 - val_output_role_loss: 0.7446 - val_output_timestamp_loss: 0.5095 - val_output_id_accuracy: 0.0033 - val_output_resource_accuracy: 0.9286 - val_output_activity_accuracy: 0.7494 - val_output_role_accuracy: 0.8126 - val_output_timestamp_mse: 0.5095
Epoch 11/20
23/23 [==============================] - 14s 586ms/step - loss: 8.7324 - output_id_loss: 8.1724 - output_resource_loss: 0.0207 - output_activity_loss: 0.2334 - output_role_loss: 0.0689 - output_timestamp_loss: 0.2370 - output_id_accuracy: 0.0076 - output_resource_accuracy: 0.9988 - output_activity_accuracy: 0.9591 - output_role_accuracy: 0.9923 - output_timestamp_mse: 0.2370 - val_loss: 13.3821 - val_output_id_loss: 10.9909 - val_output_resource_loss: 0.1414 - val_output_activity_loss: 1.1576 - val_output_role_loss: 0.6409 - val_output_timestamp_loss: 0.4513 - val_output_id_accuracy: 0.0041 - val_output_resource_accuracy: 0.9430 - val_output_activity_accuracy: 0.7531 - val_output_role_accuracy: 0.8233 - val_output_timestamp_mse: 0.4513
Epoch 12/20
23/23 [==============================] - 9s 381ms/step - loss: 8.5775 - output_id_loss: 8.0503 - output_resource_loss: 0.0190 - output_activity_loss: 0.2069 - output_role_loss: 0.0634 - output_timestamp_loss: 0.2379 - output_id_accuracy: 0.0078 - output_resource_accuracy: 0.9988 - output_activity_accuracy: 0.9649 - output_role_accuracy: 0.9917 - output_timestamp_mse: 0.2379 - val_loss: 13.2713 - val_output_id_loss: 11.1496 - val_output_resource_loss: 0.1181 - val_output_activity_loss: 1.0178 - val_output_role_loss: 0.5827 - val_output_timestamp_loss: 0.4032 - val_output_id_accuracy: 0.0045 - val_output_resource_accuracy: 0.9542 - val_output_activity_accuracy: 0.7626 - val_output_role_accuracy: 0.8279 - val_output_timestamp_mse: 0.4032
Epoch 13/20
23/23 [==============================] - 9s 413ms/step - loss: 8.4215 - output_id_loss: 7.9329 - output_resource_loss: 0.0181 - output_activity_loss: 0.1799 - output_role_loss: 0.0576 - output_timestamp_loss: 0.2329 - output_id_accuracy: 0.0099 - output_resource_accuracy: 0.9987 - output_activity_accuracy: 0.9710 - output_role_accuracy: 0.9925 - output_timestamp_mse: 0.2329 - val_loss: 13.2108 - val_output_id_loss: 11.3038 - val_output_resource_loss: 0.1050 - val_output_activity_loss: 0.9091 - val_output_role_loss: 0.5347 - val_output_timestamp_loss: 0.3582 - val_output_id_accuracy: 0.0045 - val_output_resource_accuracy: 0.9593 - val_output_activity_accuracy: 0.7732 - val_output_role_accuracy: 0.8345 - val_output_timestamp_mse: 0.3582
Epoch 14/20
23/23 [==============================] - 10s 441ms/step - loss: 8.2810 - output_id_loss: 7.8210 - output_resource_loss: 0.0167 - output_activity_loss: 0.1623 - output_role_loss: 0.0513 - output_timestamp_loss: 0.2297 - output_id_accuracy: 0.0100 - output_resource_accuracy: 0.9989 - output_activity_accuracy: 0.9735 - output_role_accuracy: 0.9941 - output_timestamp_mse: 0.2297 - val_loss: 13.1568 - val_output_id_loss: 11.4221 - val_output_resource_loss: 0.0792 - val_output_activity_loss: 0.8306 - val_output_role_loss: 0.5049 - val_output_timestamp_loss: 0.3200 - val_output_id_accuracy: 0.0045 - val_output_resource_accuracy: 0.9684 - val_output_activity_accuracy: 0.7928 - val_output_role_accuracy: 0.8440 - val_output_timestamp_mse: 0.3200
Epoch 15/20
23/23 [==============================] - 12s 518ms/step - loss: 8.1613 - output_id_loss: 7.7148 - output_resource_loss: 0.0149 - output_activity_loss: 0.1493 - output_role_loss: 0.0500 - output_timestamp_loss: 0.2324 - output_id_accuracy: 0.0112 - output_resource_accuracy: 0.9996 - output_activity_accuracy: 0.9734 - output_role_accuracy: 0.9941 - output_timestamp_mse: 0.2324 - val_loss: 13.1647 - val_output_id_loss: 11.5208 - val_output_resource_loss: 0.0647 - val_output_activity_loss: 0.7816 - val_output_role_loss: 0.5017 - val_output_timestamp_loss: 0.2960 - val_output_id_accuracy: 0.0045 - val_output_resource_accuracy: 0.9754 - val_output_activity_accuracy: 0.7979 - val_output_role_accuracy: 0.8524 - val_output_timestamp_mse: 0.2960
Epoch 16/20
23/23 [==============================] - 11s 488ms/step - loss: 8.0449 - output_id_loss: 7.6145 - output_resource_loss: 0.0155 - output_activity_loss: 0.1365 - output_role_loss: 0.0455 - output_timestamp_loss: 0.2329 - output_id_accuracy: 0.0134 - output_resource_accuracy: 0.9984 - output_activity_accuracy: 0.9766 - output_role_accuracy: 0.9942 - output_timestamp_mse: 0.2329 - val_loss: 13.1253 - val_output_id_loss: 11.5731 - val_output_resource_loss: 0.0522 - val_output_activity_loss: 0.7409 - val_output_role_loss: 0.4862 - val_output_timestamp_loss: 0.2729 - val_output_id_accuracy: 0.0047 - val_output_resource_accuracy: 0.9829 - val_output_activity_accuracy: 0.8043 - val_output_role_accuracy: 0.8566 - val_output_timestamp_mse: 0.2729
Epoch 17/20
23/23 [==============================] - 14s 599ms/step - loss: 7.9260 - output_id_loss: 7.5163 - output_resource_loss: 0.0138 - output_activity_loss: 0.1254 - output_role_loss: 0.0436 - output_timestamp_loss: 0.2270 - output_id_accuracy: 0.0153 - output_resource_accuracy: 0.9990 - output_activity_accuracy: 0.9786 - output_role_accuracy: 0.9943 - output_timestamp_mse: 0.2270 - val_loss: 13.1995 - val_output_id_loss: 11.6704 - val_output_resource_loss: 0.0480 - val_output_activity_loss: 0.7297 - val_output_role_loss: 0.4944 - val_output_timestamp_loss: 0.2570 - val_output_id_accuracy: 0.0047 - val_output_resource_accuracy: 0.9864 - val_output_activity_accuracy: 0.8033 - val_output_role_accuracy: 0.8572 - val_output_timestamp_mse: 0.2570
Epoch 18/20
23/23 [==============================] - 16s 714ms/step - loss: 7.8222 - output_id_loss: 7.4216 - output_resource_loss: 0.0132 - output_activity_loss: 0.1158 - output_role_loss: 0.0413 - output_timestamp_loss: 0.2302 - output_id_accuracy: 0.0188 - output_resource_accuracy: 0.9990 - output_activity_accuracy: 0.9789 - output_role_accuracy: 0.9943 - output_timestamp_mse: 0.2302 - val_loss: 13.1709 - val_output_id_loss: 11.6687 - val_output_resource_loss: 0.0434 - val_output_activity_loss: 0.7184 - val_output_role_loss: 0.4996 - val_output_timestamp_loss: 0.2408 - val_output_id_accuracy: 0.0050 - val_output_resource_accuracy: 0.9880 - val_output_activity_accuracy: 0.8083 - val_output_role_accuracy: 0.8592 - val_output_timestamp_mse: 0.2408
Epoch 19/20
23/23 [==============================] - 14s 633ms/step - loss: 7.7256 - output_id_loss: 7.3329 - output_resource_loss: 0.0131 - output_activity_loss: 0.1099 - output_role_loss: 0.0403 - output_timestamp_loss: 0.2294 - output_id_accuracy: 0.0193 - output_resource_accuracy: 0.9991 - output_activity_accuracy: 0.9812 - output_role_accuracy: 0.9949 - output_timestamp_mse: 0.2294 - val_loss: 13.2328 - val_output_id_loss: 11.7186 - val_output_resource_loss: 0.0443 - val_output_activity_loss: 0.7254 - val_output_role_loss: 0.5126 - val_output_timestamp_loss: 0.2319 - val_output_id_accuracy: 0.0058 - val_output_resource_accuracy: 0.9891 - val_output_activity_accuracy: 0.8109 - val_output_role_accuracy: 0.8586 - val_output_timestamp_mse: 0.2319
Epoch 20/20
23/23 [==============================] - 11s 495ms/step - loss: 7.6216 - output_id_loss: 7.2444 - output_resource_loss: 0.0122 - output_activity_loss: 0.0988 - output_role_loss: 0.0382 - output_timestamp_loss: 0.2280 - output_id_accuracy: 0.0249 - output_resource_accuracy: 0.9989 - output_activity_accuracy: 0.9823 - output_role_accuracy: 0.9945 - output_timestamp_mse: 0.2280 - val_loss: 13.2563 - val_output_id_loss: 11.7483 - val_output_resource_loss: 0.0444 - val_output_activity_loss: 0.7214 - val_output_role_loss: 0.5121 - val_output_timestamp_loss: 0.2300 - val_output_id_accuracy: 0.0062 - val_output_resource_accuracy: 0.9895 - val_output_activity_accuracy: 0.8111 - val_output_role_accuracy: 0.8592 - val_output_timestamp_mse: 0.2300

In [18]:
# Evaluate the model on the validation set
results = model.evaluate(
    [test_id, test_resource, test_activity, test_role, test_timestamp],
    [test_targets_id_cat, test_targets_resource_cat, test_targets_activity_cat, test_targets_role_cat, test_targets_timestamp],
    batch_size=64
)

print(f"Validation Loss: {results[0]}, Validation Accuracy: {results[1]}")

76/76 [==============================] - 3s 43ms/step - loss: 13.2563 - output_id_loss: 11.7483 - output_resource_loss: 0.0444 - output_activity_loss: 0.7214 - output_role_loss: 0.5121 - output_timestamp_loss: 0.2300 - output_id_accuracy: 0.0062 - output_resource_accuracy: 0.9895 - output_activity_accuracy: 0.8111 - output_role_accuracy: 0.8592 - output_timestamp_mse: 0.2300
Validation Loss: 13.256266593933105, Validation Accuracy: 11.748291015625

# Anomaly Score Computation

In [19]:
# Generate predictions for all inputs
predictions = model.predict([windows_id, windows_resource, windows_activity, windows_role, windows_timestamp])

# Extract predictions for categorical attributes (softmax probabilities)
predictions_id = predictions[0]        # ID predictions
predictions_resource = predictions[1]  # Resource predictions
predictions_activity = predictions[2]  # Activity predictions
predictions_role = predictions[3]      # Role predictions

# Extract predictions for the continuous attribute (timestamp)
predictions_timestamp = predictions[4]  # Timestamp predictions

505/505 [==============================] - 20s 15ms/step

In [20]:
import numpy as np

def calculate_anomaly_scores(predictions, targets):
    scores = []
    # Loop through each example in the predictions
    for i in range(predictions.shape[0]):
        actual_prob = predictions[i, targets[i]]  # Extract the probability of the true class using target index
        # Calculate anomaly score as sum of probabilities greater than the probability of the actual value
        anomaly_score = np.sum(predictions[i][predictions[i] > actual_prob])
        scores.append(anomaly_score)

    return scores

In [21]:
# Calculate anomaly scores for each attribute type
anomaly_scores_id = calculate_anomaly_scores(predictions_id, targets_id.astype(int))
anomaly_scores_resource = calculate_anomaly_scores(predictions_resource, targets_resource.astype(int))
anomaly_scores_activity = calculate_anomaly_scores(predictions_activity, targets_activity.astype(int))
anomaly_scores_role = calculate_anomaly_scores(predictions_role, targets_role.astype(int))

In [22]:
def compute_anomaly_scores_continuous(predictions, actuals):
    # Calculate absolute differences
    differences = np.abs(predictions - actuals)
    
    # Normalize to [0, 1] range
    max_diff = np.max(differences)
    normalized_scores = differences / max_diff if max_diff != 0 else differences
    
    return normalized_scores

In [23]:
anomaly_scores_timestamp = compute_anomaly_scores_continuous(predictions_timestamp, targets_timestamp)
anomaly_scores_timestamp = anomaly_scores_timestamp.flatten()
anomaly_scores_timestamp = anomaly_scores_timestamp.tolist()

## Insert missing scores for cases with less than 2 Events

In [24]:
import pandas as pd

# Create a DataFrame from the case_indices_array corresponding to case_resource
score = pd.DataFrame({'case': case_indices})
score['score_id'] = anomaly_scores_id
score['score_resource'] = anomaly_scores_resource
score['score_activity'] = anomaly_scores_activity
score['score_role'] = anomaly_scores_role
score['score_timestamp'] = anomaly_scores_timestamp

score['case'] = score['case'].astype(int)

score

,case,score_id,score_resource,score_activity,score_role,score_timestamp
0,0,0.037058,0.000000,0.000000,0.000000,0.003711
1,0,0.011951,0.000000,0.000000,0.000000,0.030838
2,0,0.002503,0.000000,0.000000,0.000000,0.029228
3,0,0.986840,0.972375,0.998833,0.994504,0.112436
4,0,0.003785,0.000000,0.768325,0.806997,0.471330
...,...,...,...,...,...,...
16142,2097,0.985931,0.000000,0.000000,0.000000,0.002445
16143,2098,0.004400,0.000000,0.000000,0.000000,0.024217
16144,2098,0.998688,0.000000,0.000000,0.000000,0.035341
16145,2098,0.003734,0.000000,0.000000,0.000000,0.034229
16146,2098,0.103412,0.000000,0.000000,0.000000,0.019142

In [25]:
import pandas as pd

def contains_all_values(df, column, end):

    # Generate the set of all values in the specified range
    required_values = set(range(0, end + 1))
    
    # Get the unique values in the specified column
    column_values = set(df[column].unique())
    
    # Find missing values
    missing_values = required_values - column_values
    
    # Print missing values if any
    if missing_values:
        print(f"Missing values: {sorted(missing_values)}")
    
    # Check if all required values are in the column values
    return required_values.issubset(column_values)

end = 2098

result = contains_all_values(score, 'case', end)
print(f"Does the 'case' column contain all values between 0 and {end}? {result}")

Missing values: [87, 166, 1081, 1139, 1301, 1586, 1835]
Does the 'case' column contain all values between 0 and 2098? False

In [26]:
# Generate the full range of values
full_range = set(range(2098+1))

# Get the existing 'case' values
existing_cases = set(score['case'])

# Identify missing values
missing_cases = full_range - existing_cases

# Create a DataFrame for missing values
missing_df = pd.DataFrame({'case': list(missing_cases)})

# Add other columns with value 1
for col in score.columns:
    if col != 'case':
        missing_df[col] = 1

# Concatenate the original DataFrame with the missing values DataFrame
updated_score = pd.concat([score, missing_df])

# Sort the DataFrame by 'case'
updated_score = updated_score.sort_values(by='case').reset_index(drop=True)

updated_score

,case,score_id,score_resource,score_activity,score_role,score_timestamp
0,0,0.037058,0.000000,0.000000,0.000000,0.003711
1,0,0.011951,0.000000,0.000000,0.000000,0.030838
2,0,0.002503,0.000000,0.000000,0.000000,0.029228
3,0,0.986840,0.972375,0.998833,0.994504,0.112436
4,0,0.003785,0.000000,0.768325,0.806997,0.471330
...,...,...,...,...,...,...
16149,2097,0.031568,0.000000,0.000000,0.000000,0.011871
16150,2098,0.998688,0.000000,0.000000,0.000000,0.035341
16151,2098,0.003734,0.000000,0.000000,0.000000,0.034229
16152,2098,0.103412,0.000000,0.000000,0.000000,0.019142
16153,2098,0.004400,0.000000,0.000000,0.000000,0.024217

In [27]:
anomaly_scores_id = updated_score['score_id']
anomaly_scores_resource = updated_score['score_resource']
anomaly_scores_activity = updated_score['score_activity']
anomaly_scores_role = updated_score['score_role']
anomaly_scores_timestamp = updated_score['score_timestamp']

### Threshold (lowest plateau)

In [28]:
import numpy as np

def calculate_anomaly_ratio(scores, threshold):
    """
    Calculate the anomaly ratio for a given threshold.
    """
    return np.mean(scores > threshold)

def find_plateaus(scores, epsilon=1e-4, min_plateau_length=10):
    """
    Identify the lowest plateau in the anomaly ratio function and calculate the mean-centered threshold.
    """
    scores = np.array(scores)  # Convert scores to a NumPy array
    sorted_scores = np.sort(scores)
    
    # Remove duplicate values
    unique_thresholds, unique_indices = np.unique(sorted_scores, return_index=True)
    anomaly_ratios = np.array([calculate_anomaly_ratio(scores, t) for t in unique_thresholds])
    
    # Calculate first and second derivatives
    first_derivatives = np.diff(anomaly_ratios) / np.diff(unique_thresholds)
    second_derivatives = np.diff(first_derivatives) / np.diff(unique_thresholds[:-1])
    
    # Identify plateaus where the first derivative is close to zero
    plateau_indices = np.where(np.abs(first_derivatives) < epsilon)[0]
    
    # Group consecutive indices to identify continuous plateaus
    grouped_plateaus = np.split(plateau_indices, np.where(np.diff(plateau_indices) != 1)[0] + 1)
    
    # Filter plateaus based on minimum length
    long_plateaus = [g for g in grouped_plateaus if len(g) >= min_plateau_length]
    
    if long_plateaus:
        # Take the first long plateau and find the mean threshold in this plateau
        first_plateau = long_plateaus[0]
        plateau_thresholds = unique_thresholds[first_plateau]
        return np.mean(plateau_thresholds)
    else:
        # If no plateau is found, return a default value, e.g., the 90th percentile
        percentile_90 = np.percentile(sorted_scores, 90)
        if percentile_90 == 1.0:
            return 0.4
        else:
            return percentile_90

In [29]:
threshold_id = find_plateaus(anomaly_scores_id)
threshold_resource = find_plateaus(anomaly_scores_resource)
threshold_activity = find_plateaus(anomaly_scores_activity)
threshold_role = find_plateaus(anomaly_scores_role)
threshold_timestamp = find_plateaus(anomaly_scores_timestamp)

### Detection

In [30]:
def detect_anomalies(anomaly_scores, threshold):
    labels = [1 if score > threshold else 0 for score in anomaly_scores]
    return labels

In [31]:
# Detect anomalies based on the calculated anomaly scores and thresholds
labels_id = detect_anomalies(anomaly_scores_id, threshold_id)
labels_resource = detect_anomalies(anomaly_scores_resource, threshold_resource)
labels_activity = detect_anomalies(anomaly_scores_activity, threshold_activity)
labels_role = detect_anomalies(anomaly_scores_role, threshold_role)
labels_timestamp = detect_anomalies(anomaly_scores_timestamp, threshold_timestamp)

# Mapping

In [32]:
case_indices = updated_score['case']

In [33]:
import pandas as pd

# Create a DataFrame from the case_indices_array corresponding to case_resource
mapping = pd.DataFrame({'case': case_indices})
mapping['predicted_id'] = labels_id
mapping['predicted_resource'] = labels_resource
mapping['predicted_activity'] = labels_activity
mapping['predicted_role'] = labels_role
mapping['predicted_timestamp'] = labels_timestamp

mapping

,case,predicted_id,predicted_resource,predicted_activity,predicted_role,predicted_timestamp
0,0,0,0,0,0,0
1,0,0,0,0,0,0
2,0,0,0,0,0,0
3,0,0,1,1,1,1
4,0,0,0,1,1,1
...,...,...,...,...,...,...
16149,2097,0,0,0,0,0
16150,2098,1,0,0,0,0
16151,2098,0,0,0,0,0
16152,2098,0,0,0,0,0
16153,2098,0,0,0,0,0

In [34]:
# Create a boolean DataFrame where each value is True if the value is 1
contains_one = (mapping[['predicted_resource', 'predicted_activity', 'predicted_role', 'predicted_timestamp']] == 1)

# Group by 'case' and check if there's at least one 'True' in any of the columns
case_prediction = contains_one.groupby(mapping['case']).any().any(axis=1)
case_prediction

case
0        True
1        True
2        True
3        True
4        True
        ...
2094     True
2095     True
2096    False
2097    False
2098    False
Length: 2099, dtype: bool

# Ground Truth

In [35]:
def generate_alignments_adjusted_tracecost_pkl(log, net, initial_marking, final_marking):
    from pm4py.algo.conformance.alignments.petri_net import algorithm as alignments
    from pm4py.algo.conformance.alignments.petri_net import variants
    from pm4py.objects.petri_net.utils import align_utils
    max_events=0
    for trace in log:
        counter=0
        for event in trace:
            counter+=1
        if counter > max_events:
            max_events=counter
    parameters={}
    parameters[alignments.Variants.VERSION_STATE_EQUATION_A_STAR.value.Parameters.PARAM_SYNC_COST_FUNCTION] = list(map(lambda i: .1*i, range(max_events*2)))
    parameters[alignments.Variants.VERSION_STATE_EQUATION_A_STAR.value.Parameters.PARAM_TRACE_COST_FUNCTION]=list(map(lambda i: align_utils.STD_MODEL_LOG_MOVE_COST-.1*i, range(max_events*2)))
    aligned_traces = alignments.apply_log(log, net, initial_marking, final_marking, variant=variants.state_equation_a_star, parameters=parameters)
    return aligned_traces

In [36]:
import pm4py
from pm4py.objects.log.importer.xes import importer as xes_importer
from pm4py.objects.bpmn.importer import importer as bpmn_importer
from pm4py.algo.conformance.alignments.petri_net import algorithm as alignments_petri

# 2. Import the given BPMN model
bpmn_graph = bpmn_importer.apply("../../data/model/Model_PrepaidTravelCost.bpmn")

# 3. Convert the BPMN to a Petri net
net, initial_marking, final_marking = pm4py.convert_to_petri_net(bpmn_graph)

aligned_traces = generate_alignments_adjusted_tracecost_pkl(log, net, initial_marking, final_marking)

aligning log, completed variants ::   0%|          | 0/202 [00:00<?, ?it/s]

In [37]:
def extract_conformance_status_by_fitness(aligned_traces):
    conformance_status = []
    for alignment in aligned_traces:
        fitness = alignment['fitness']
        # If the fitness is 1.0, the trace is conforming
        if fitness == 1.0:
            conformance_status.append(0)
        else:
            conformance_status.append(1)
    return conformance_status

# Get the conformance status list from the aligned traces
conformance = extract_conformance_status_by_fitness(aligned_traces)

In [38]:
ground_truth = pd.DataFrame({'conformity': conformance})
ground_truth['predicted'] = case_prediction

# Convert False to 0 and True to 1
ground_truth['predicted'] = [int(value) for value in ground_truth['predicted']]
ground_truth

      conformity  predicted
0              1          1
1              1          1
2              1          1
3              1          1
4              1          1
...          ...        ...
2094           1          1
2095           1          1
2096           1          0
2097           1          0
2098           1          0

[2099 rows x 2 columns]

# Evaluation

In [39]:
# Calculating TP, TN, FP, FN
TP = ((ground_truth['conformity'] == 1) & (ground_truth['predicted'] == 1)).sum()
TN = ((ground_truth['conformity'] == 0) & (ground_truth['predicted'] == 0)).sum()
FP = ((ground_truth['conformity'] == 0) & (ground_truth['predicted'] == 1)).sum()
FN = ((ground_truth['conformity'] == 1) & (ground_truth['predicted'] == 0)).sum()

In [40]:
precision_dev = TP / (TP + FP)
print(f"Precision Dev: {precision_dev:.2f}")

Precision Dev: 0.48

In [41]:
recall_dev = TP / (TP + FN)
print(f"Recall Dev: {recall_dev:.2f}")

Recall Dev: 0.71

In [42]:
precision_no_dev = TN / (TN + FN)
print(f"Precision No Dev: {precision_no_dev:.2f}")

Precision No Dev: 0.65

In [43]:
recall_no_dev = TN / (TN + FP)
print(f"Recall No Dev: {recall_no_dev:.2f}")

Recall No Dev: 0.41

In [44]:
from sklearn.metrics import roc_auc_score

auc_roc = roc_auc_score(ground_truth['conformity'], ground_truth['predicted'])
print(f"AUC-ROC: {auc_roc:.2f}")

AUC-ROC: 0.56